detail/urls.py
from django.urls import path
from . import views

# TODO: Add a new page: Compare two species/hybrids
# TODO: Add feature search page - search by color, features
# TODO: Add search by ancestors pair.
# TODO: Add search by location

app_name = 'detail'
urlpatterns = [
    # detail
    # path('selectspecies/<int:pid>/', views.selectspecies, name='selectspecies'),
    # path('nav/', views.nav, name='nav'),
    path('species/', views.information, name='information'),
    path('species/<int:pid>/', views.information, name='information'),
    path('hybrid/', views.information, name='information'),
    path('hybrid/<int:pid>/', views.information, name='information'),
    path('<int:pid>/species/', views.information, name='information'),
    path('<int:pid>/species_detail/', views.information, name='information'),
    path('<int:pid>/hybrid/', views.information, name='information'),
    path('<int:pid>/hybrid_detail/', views.information, name='information'),
    path('compare/<int:pid>/', views.compare, name='compare'),
    path('compare/', views.compare, name='compare'),
    path('createhybrid/', views.createhybrid, name='createhybrid'),
    path('information/<int:pid>/', views.information, name='information'),
    path('information/', views.information, name='information'),

    path('ancestor/', views.ancestor, name='ancestor'),
    path('ancestor/<int:pid>/', views.ancestor, name='ancestor'),
    path('ancestrytree/<int:pid>/', views.ancestrytree, name='ancestrytree'),
    path('ancestrytree/', views.ancestrytree, name='ancestrytree'),
    path('progeny/<int:pid>/', views.progeny, name='progeny'),
    path('progenyimg/<int:pid>/', views.progenyimg, name='progenyimg'),

    path('comment/', views.comment, name='comment'),
    path('comments/', views.comments, name='comments'),
    path('myphoto/<int:pid>/', views.myphoto, name='myphoto'),
    path('myphoto/', views.myphoto, name='myphoto'),
    path('myphoto_browse_spc/', views.myphoto_browse_spc, name='myphoto_browse_spc'),
    path('myphoto_browse_hyb/', views.myphoto_browse_hyb, name='myphoto_browse_hyb'),
    path('curate/<int:pid>/', views.curate, name='curate'),
    path('<int:pid>/photos/', views.photos, name='photos'),
    path('photos/<int:pid>/', views.photos, name='photos'),
    path('curateinfospc/<int:pid>/', views.curateinfospc, name='curateinfospc'),
    path('curateinfospc/', views.curateinfospc, name='curateinfospc'),
    path('curateinfohyb/<int:pid>/', views.curateinfohyb, name='curateinfohyb'),
    path('curateinfohyb/', views.curateinfohyb, name='curateinfohyb'),
    path('curate_newupload/', views.curate_newupload, name='curate_newupload'),
    path('curate_pending/', views.curate_pending, name='curate_pending'),
    path('curate_newapproved/', views.curate_newapproved, name='curate_newapproved'),
    path('reidentify/<int:orid>/<int:pid>/', views.reidentify, name='reidentify'),

    path('uploadfile/<int:pid>/', views.uploadfile, name='uploadfile'),
    path('uploadweb/<int:pid>/', views.uploadweb, name='uploadweb'),
    path('uploadweb/<int:pid>/<int:orid>/', views.uploadweb, name='uploadweb'),
    path('deletephoto/<int:orid>/', views.deletephoto, name='deletephoto'),
    path('deletewebphoto/<int:pid>/', views.deletewebphoto, name='deletewebphoto'),
    path('approvemediaphoto/<int:pid>/', views.approvemediaphoto, name='approvemediaphoto'),
]

documents/urls.py
from django.urls import path
from . import views

# Documentations

app_name = 'documents'
urlpatterns = [
    # path('about/', views.about, name='about'),
    path('articles/', views.articles, name='articles'),
    path('bylaws/', views.bylaws, name='bylaws'),
    path('changes/', views.changes, name='changes'),
    path('contact/', views.contact, name='contact'),
    path('curator/', views.curator, name='curator'),
    path('development/', views.development, name='development'),
    path('datamodel/', views.datamodel, name='datamodel'),
    path('disclaimer/', views.disclaimer, name='disclaimer'),
    path('faq/', views.faq, name='faq'),
    path('future_development/', views.future_development, name='future_development'),
    path('greetings/', views.greetings, name='greetings'),
    path('help/', views.help, name='help'),
    path('identinstruction/', views.identinstruction, name='identinstruction'),
    # path('instructionupload_curate/', views.instructionupload_curate, name='instructionupload_curate'),
    # path('instructionupload_private/', views.instructionupload_private, name='instructionupload_private'),
    # path('instructionupload_file/', views.instructionupload_file, name='instructionupload_file'),
    path('instructionupload/', views.instructionupload, name='instructionupload'),
    path('list/', views.list, name='list'),
    path('migration/', views.migration, name='migration'),
    path('maintenance/', views.maintenance, name='maintenance'),
    path('navigation/', views.navigation, name='navigation'),
    path('photosubmissionguideline/', views.photosubmissionguideline, name='photosubmissionguideline'),
    path('photoacquisionguideline/', views.photoacquisionguideline, name='photoacquisionguideline'),
    path('privacy_policy/', views.privacy_policy, name='privacy_policy'),
    path('req501c3/', views.req501c3, name='req501c3'),
    path('releasenote_v4/', views.releasenote_v4, name='releasenote_v4'),
    path('termsofuse/', views.termsofuse, name='termsofuse'),
    path('whoweare/', views.whoweare, name='whoweare'),

    # path('assets/$', views.assets, name='assets'),
    # path('copyright/', views.copyright, name='copyright'),
    # path('newrelease/', views.newrelease, name='newrelease'),
    # path('personnel/', views.personnel, name='personnel'),
    # path('project/', views.project, name='project'),
    # path('statistics/', views.statistics, name='statistics'),
    # path('submission/', views.photo_submission, name='submission'),
    # path('rvolunteer/', views.volunteer, name='volunteer'),
]

donation/urls.py
from django.urls import path, re_path

from . import views

app_name = 'donation'
urlpatterns = [
    path('donateapp/', views.DonateView.as_view(), name='donateapp'),
    path('donateapp/<int:donateamt>/', views.DonateView.as_view(), name='donateapp'),
    path('donate/', views.donate, name='donate'),
    path('donate/<int:donateamt>/', views.donate, name='donate'),
    path('donate/paypal-done/', views.PaypalTransactionDoneView.as_view(), name='paypal-done'),
    path('thank-you/<int:donateamt>/', views.ThankYouView.as_view(), name='thankyou'),
]

myproject/urls.py
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.generic import TemplateView
from django.views.generic.base import TemplateView
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from accounts.views import  user_reset_password, login_page, register_page, UpdateProfileView, SetEmailView,\
    ChangeEmailView, PasswordChangeRedirect, CustomPasswordResetFromKeyView
from myproject.views import orchid_home
from myproject.views import robots_txt

urlpatterns = [
    path('admin/', admin.site.urls),
    # path("robots.txt", robots_txt),
    path("robots.txt", TemplateView.as_view(template_name="robots.txt", content_type="text/plain"),
    path('', orchid_home, name='orchid_home'),

    path('login/', login_page, name='login'),
    path('register/', register_page, name='register'),
    path('set_email/', SetEmailView.as_view(), name='set_email'),
    path('change_email/', ChangeEmailView.as_view(), name='change_email'),
    path('update_profile/', UpdateProfileView.as_view(), name='update_profile'),
    path('logout/', LogoutView.as_view(), {'next_page': '//'}, name='logout'),
    path('accounts/password/change/', PasswordChangeRedirect.as_view(), name="account_password_change"),
    
    path('accounts/password/user_reset_password/', user_reset_password, name="user_account_reset_password"),
    re_path(
        r"^accounts/password/reset/key/(?P<uidb36>[0-9A-Za-z]+)-(?P<key>.+)/$",
        CustomPasswordResetFromKeyView.as_view(),
        name="account_reset_password_from_key",
    ),
    path('accounts/', include('allauth.urls')),
    # path('password_reset/', include(password_reset.urls)),

    path('search/', include('search.urls')),
    path('orchidlist/', include('orchidlist.urls')),
    path('detail/', include('detail.urls')),
    path('documents/', include('documents.urls')),
    path('donation/', include('donation.urls')),

    # old
    path('natural/', include('natural.urls')),
    path('orchid/', include('orchid.urls')),
    path('orchidlite/', include('orchidlite.urls')),

    # path('sendmail/', include('sendmail.urls')),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

orchidlist/urls.py
# from django.conf.urls import url, include
from django.urls import path
from . import views

# TODO: Add a new page: Compare two species/hybrids
# TODO: Add feature search page - search by color, features
# TODO: Add search by ancestors pair.
# TODO: Add search by location

app_name = 'orchidlist'
urlpatterns = [
    # Lists
    path('family/', views.family, name='family'),
    path('subfamily/', views.subfamily, name='subfamily'),
    path('tribe/', views.tribe, name='tribe'),
    path('subtribe/', views.subtribe, name='subtribe'),
    path('genera/', views.genera, name='genera'),
    path('species/', views.species_list, name='species'),
    path('hybrid/', views.hybrid_list, name='hybrid'),
    path('progeny/<int:pid>/', views.progeny, name='progeny'),
    path('progeny/', views.progeny, name='progeny'),
    path('progenyimg/<int:pid>/', views.progenyimg, name='progenyimg'),
    path('progenyimg/', views.progenyimg, name='progenyimg'),
    path('subgenus/', views.subgenus, name='subgenus'),
    path('section/', views.section, name='section'),
    path('subsection/', views.subsection, name='subsection'),
    path('series/', views.series, name='series'),
    path('advanced/', views.advanced, name='advanced'),
    path('browsegen/', views.browsegen, name='browsegen'),
    path('browse/', views.browse, name='browse'),
    path('browsedist/', views.browsedist, name='browsedist'),

    # Legacy urls
]

search/urls.py
from django.urls import path, re_path
from . import views

app_name = 'search'
urlpatterns = [
    # Top level
    path('search_match/', views.search_match, name='search_match'),
    path('search_fuzzy/', views.search_fuzzy, name='search_fuzzy'),
]

myproject/views.py
from django.shortcuts import render
from django.http import HttpResponse
from datetime import datetime, timedelta
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from django.apps import apps
from django.views.decorators.http import require_GET
from detail.views import getRole
import random
import string

Genus = apps.get_model('orchiddb', 'Genus')
Species = apps.get_model('orchiddb', 'Species')
SpcImages = apps.get_model('orchiddb', 'SpcImages')
HybImages = apps.get_model('orchiddb', 'HybImages')
Comment = apps.get_model('orchiddb', 'Comment')
num_img = 20



@require_GET
def robots_txt(request):
    lines = [
        "User-Agent: *",
        "Disallow: /accounts/",
        "Disallow: /detail/photos/",
        "Disallow: /documents/",
        "Disallow: /natural/",
        "Disallow: /orchid/",
        "Disallow: /orchidlist/",
        "Disallow: /orchidlight/",
        "Disallow: /orchiddb/",
        "Disallow: /search/",
        "User-Agent: PetalBot",
        "Disallow: /",

    ]
    return HttpResponse("\n".join(lines), content_type="text/plain")


def orchid_home(request):
    randgenus = Genus.objects.exclude(status='synonym').extra(where=["num_spc_with_image + num_hyb_with_image > 0"]
                                                              ).values_list('pid', flat=True).order_by('?')
    # Number of visits to this view, as counted in the session variable.
    # num_visits = request.session.get('num_visits', 0)
    # request.session['num_visits'] = num_visits + 1
    randimages = []
    for e in randgenus:
        if len(randimages) >= num_img:
            break
        if SpcImages.objects.filter(gen=e):
            img = SpcImages.objects.filter(gen=e).filter(rank__gt=0).filter(rank__lt=7).order_by('-rank', 'quality', '?'
                                                                                                 )[0:1]
            if img and len(img):
                randimages.append(img[0])

    random.shuffle(randimages)
    role = getRole(request)
    if 'role' in request.GET:
        role = request.GET['role']
    context = {'title': 'orchid_home', 'role': role, 'randimages': randimages, 'level': 'detail', 'tab': 'sum', }
    return render(request, 'orchid_home.html', context)


# def require_get(view_func):
#     def wrap(request, *args, **kwargs):
#         if request.method != "GET":
#             return HttpResponseBadRequest("Expecting GET request")
#         return view_func(request, *args, **kwargs)
#     wrap.__doc__ = view_func.__doc__
#     wrap.__dict__ = view_func.__dict__
#     wrap.__name__ = view_func.__name__
#     return wrap
#
#
# @require_get
# def robots_txt(request):
#     lines = [
#         "User-Agent: *",
#         "Disallow: /private/",
#         "Disallow: /junk/",
#     ]
#     return HttpResponse("\n".join(lines), content_type="text/plain")

myproject/templates/dashboard.html
{% include "base.html" %}
{% block body %}
<style>

.portlet {
    background-color: white;
}
@media only screen and (max-width: 2200px) {
}

@media only screen and (max-width: 1500px) {
}

@media only screen and (max-width: 1200px) {
}


@media only screen and (max-width: 800px) {
}

@media only screen and (max-width: 580px) {
}
.thumbnails {
   object-fit: cover;
   overflow: hidden;
   height: 16vw;
   width : 16vw;
   padding:2px;
}

img{
    width:100%;
}
.widget {
    min-height: 100px;
    background-color: white;
    margin:10px;
    padding:10px;
}
    h6 {
        color: #878787;
    }
</style>
<br>
<br>
<br>

<div class="container-fluid">
    <div id="notice">
        Note: Try to add a new div with class="col" inside the row class - this will create four equal-width columns.
    </div>
    <div class="row">
        <div class="col-sm-4" style="">
            <div class="widget public">
                <h6>Classification</h6>


            </div>
            <div class="widget private">
                <h6>Genus</h6>


            </div>
            <div class="widget curate">
                <h6>Intrageneric</h6>

            </div>
        </div>

        <div class="col-sm-4" style="">
            <div class="widget public">
                <h6>Species</h6>


            </div>
            <div class="widget private">
                <h6>New Uploadded Photos</h6>


            </div>
            <div class="widget curate">
                <h6>New comments</h6>

            </div>
        </div>

        <div class="col-sm-4" style="">
            <div class="widget public">
                <h6>Hybrid</h6>


            </div>
            <div class="widget private">
                <h6>Ancestry</h6>


            </div>
            <div class="widget curate">
                <h6>Progeny</h6>

            </div>
        </div>

    </div>
</div>




{% endblock %}

myproject/templates/home.html
{% include "base.html" %}
{% block body %}
<style>

div.text-c {
    position: absolute;
    top: 10%;
    left: 50%;
    transform: translate(-50%, -50%);
    font-size: 11px;
}
.btn-side {
    width:150px;
    margin:3px;
}
.mytext {
    font-size: 13px;
}
.imgcaption {
    font-size: 10px;
    height: 20px;
    overflow: hidden;
}
.imgcaption_top {
    font-size: 16px;
    height: 20px;
    overflow: hidden;
}
.thumbnails {
   object-fit: cover;
   overflow: hidden;
   height: 14vw;
   width : 14vw;
   padding:2px;
}
.intro {
    clear:left;
    width:80%;
    font-size:14px;

}
@media only screen and (max-width: 800px) {
    .mytext {
        font-size: 11px;
    }
    .imgcaption_top {
        font-size: 14px;
        /*height: 20px;*/
        /*overflow: hidden;*/
    }
    .thumbnails {
       height: 20vw;
       width : 20vw;
    }
    div.text-c {
        font-size: 11px;
    }
    .intro {
        font-size:12px;

    }
}

@media only screen and (max-width: 580px) {
    .imgcaption_top {
        font-size: 14px;
        /*height: 20px;*/
        /*overflow: hidden;*/
    }
    .intro {
        font-size:12px;

    }
}

.box {
    position: relative;
    display: inline-block;
    text-align: center;
    color: white;
    margin: 4px 4px;
}

img{
    width:100%;
}

.btn {
    margin:2px 0;
    width: 95%;
    font-size:13px;
    color: #272ba3;
    padding:5px 0;
    background-color: white;
    border:1px solid #c6c0c0;
    border-radius: .15rem;
}
.btn:hover {
    background-color: #cad4f7;
}

    ul{
        padding-left:15px;
        font-size: 13px;
        line-height: 30px;
    }
    .partner {
        /*height:50px;*/
        width:120px;
        margin:5px;
        padding: 5px;
        line-height: 15px;
        text-align:center;
        padding:5px;
    }

</style>

<div style="clear:both"></div>

<div class="container-fluid" style="min-height:200px;border:0 solid grey">
    <div class="row">
        <div class="col-sm-2 hidden-xs" style="padding:0; border:1px solid lightgrey">
            <br><br>
            {% include "side_home.html" %}
        </div>

        <div class="col-xs-12 col-sm-10">
<!--   Orchid Roots Business-->
            <br><br>
            <div class="intro" style="clear:left; width:80%">
                <h5>OrchidRoots overview</h5>
            <p>OrchidRoots is freely available under our terms and conditions of use.  We are non-profit that survives on donations.
                If you like what we have to offer, please consider a <a href="{% url 'donation:donateapp' %}">donation</a> to support our work.</p>
            </div>
            <br><br>

            <hr>
            <br><br>
<!-- Orchid Browser -->
            <div class="intro">
                <br>
                <div style="display:inline-block;">
                    {% for image in randimagesspc %}
                        <div style="display:inline-block;">
                        <div class="imgcaption_top">
                            <a href="{% url 'orchidlist:browse' %}?type={{image.pid.pid.type}}&genus={{image.pid.pid.genus}}&display=checked"><i>{{image.pid.gen}}</i></a>
                        </div>
                        <a href="{% url 'detail:information' %}?pid={{image.pid.pid_id}}&role={{role}}">
                            <div class="box">
                                <img class="thumbnails" alt="" src="/static/utils/images/species/{{image.image_file}}">
                                <div class="text-c">{{image.pid.pid.speciesname|safe}}</div>
                            </div>



                        </a>
                        </div>
                    {% endfor %}
                    {% for image in randimageshyb %}
                        <div style="display:inline-block;">
                        <div class="imgcaption_top">
                            <i>{{image.pid.gen}}</i>
                        </div>
                        <a href="{% url 'detail:information' %}?pid={{image.pid.pid_id}}&role={{role}}">
                            <div class="box">
                                <img class="thumbnails" alt="" src="/static/utils/images/hybrid/{{image.image_file}}">
                                <div class="text-c">{{image.pid.pid.speciesname|safe}}</div>
                            </div>
                        </a>
                        </div>
                    {% endfor %}
                </div>
                <div class="clearfix"></div>
            </div>
            <hr>
            <br><br>
         </div>
    </div>
</div> <!--Summary-->






{% endblock %}

myproject/templates/orchid_home.html
{% include "base.html" %}
{% block body %}
<style>

div.text-c {
    position: absolute;
    top: 5%;
    left: 50%;
    transform: translate(-50%, -50%);
    font-size: 11px;
}
.box {
    position: relative;
    display: inline-block;
    text-align: center;
    color: white;
    margin: 4px 0;
    font-size:12px;
}

.thumbnails {
   object-fit: cover;
   overflow: hidden;
   height: 10vw;
   width : 10vw;
   padding:2px;
}


.survey {
   object-fit: cover;
   overflow: hidden;
   height: 80px;
   width : 200px;
   padding:2px;
}
@media only screen and (max-width: 800px) {
    div.text-c {
        font-size: 11px;
    }
    .thumbnails {
       height: 10vw;
       width : 10vw;
    }
}

@media only screen and (max-width: 500px) {
    .thumbnails {
        width:15vw;
        height:15vw;
    }
}


img{
    width:100%;
}


/* [3] Finally, transforming the image when container gets hovered */
.img-hover-zoom:hover img {
  transform: scale(1.5);
}
    ul{
        padding-left:15px;
        font-size: 13px;
        padding-left:10px;
        line-height: 30px;
        list-style-type:none;
    }


.btn-custom{
    margin:0;
    padding:0;
    color: #100d0d;
    width:100px !important;
    height:25px;
    font-size:14px;
    display: inline-block;
    display:inline-block;
}

.btn-custom:hover {
    text-decoration: none;
    color: darkblue;
}
</style>
<br>
<br>

<div style="clear:both"></div>

<div class="container-fluid" style="min-height:200px;border:0 solid grey">
    <div style="clear:both"></div>
    <div class="row">
        <div class="d-none d-sm-block col-sm-3 col-lg-2" style="padding:0;">
            {% include "side_home.html" %}
        </div>

        <div class="col-sm-8 col-lg-9">
            <div class="card mt-3">
                <div class="card-body" style="font-size:15px">
                    <h6 class="card-title d-inline-block">Welcome to OrchidRoots</h6>
                    <div class="d-inline-block">
                        OrchidRoots is a non-profit organization. Our goal is to provide a tool that will help
                        our users search for and find the roots of their orchids.
                        Though each member of our team works on a voluntary basis, there are ongoing costs for technology,
                        operation and new development that would require some funding. Please make a donation to help our course
                            <a class="btn btn-custom btn-outline-primary" href="{% url 'donation:donateapp' %}">HERE</a>.
                        Your donation will allow us to deliver more value and to make the world of orchids more transparent.
                        

                    </div>
                    Our survey has now been closed.  We will draw winners for a chance to win the first prize: A brand new copy of
                    "Flora of China volume 25: Orchidaceae" Missouri Botanical Press (September 28, 2009).
                    There are some consolation prizes as well.  The result summary and answers for some suggestions from
                    the survey and the name of winners will be posted in our Facebook Group BlueNanta on March 10 2021.

                    Thank you for your time to fill out the survey.  Your input will help shape future of OrchidRoots.

                    <p>

                    <form class="form-inline" action="{% url 'search:search_match' %}">
                        And now, start your journey by looking for an orchid:&nbsp;&nbsp;&nbsp;
                        <input type="hidden" name="role" value="">
                        <input type="text" class="form-control border border-right-0 searchbox" name="search" value="" onfocus="this.select()" pattern=".{3,}" placeholder="Search..." required="" title="Include genus to speed up the search." style="width:250px; border:2px solid #3b9ff7 !important;">
                    </form>

                    </p>
                </div>
            </div>

            <div class="card mt-3">
<!--                <div class="card-header">-->
<!--                    <h6 class="card-title" style="margin-bottom: 0"><a href="{% url 'orchidlist:browse' %}?role={{role}}&type={{image.pid.pid.type}}&display=checked">Browse Images</a></h6>-->
<!--                </div>-->
                <div class="card-body">
                    {% for image in randimages %}
                    {% if image.pid.pid.type == 'hybrid' %}
                        <div style="display:inline-block;">
                        <a href="{% url 'orchidlist:browse' %}?role={{role}}&type={{image.pid.pid.type}}&genus={{image.pid.pid.genus}}&display=checked">
                            <div class="box">
                                <img class="thumbnails" alt="" src="/static/utils/images/hybrid/{{image.image_file}}">
<!--                                <div class="text-c">{{image.pid.pid.speciesname|safe}}</div>-->
                            </div>
                        </a>
                        </div>
                    {% else %}
                        <div style="display:inline-block;">
                        <a href="{% url 'orchidlist:browse' %}?role={{role}}&type={{image.pid.pid.type}}&genus={{image.pid.pid.genus}}&display=checked">
                            <div class="box">
                                <img class="thumbnails" alt="" src="/static/utils/images/species/{{image.image_file}}">
                            </div>
                        </a>
                        </div>
                    {% endif %}

                    {% endfor %}
                </div>
                <div class="clearfix"></div>
            </div>


            <br>
        </div>
    </div>




</div> <!--Summary-->






{% endblock %}

myproject/templates/side_home.html
<!--<div style="clear:both"></div>-->
<style>
    .li-side {
        list-style:none;
        width:100%;
        padding: 0 5px;
    }

.bannerfont {
    font-size:14px;
}
.sidebtn {
    margin:2px 0;
    width: 95%;
    font-size:13px;
    color: #272ba3;
    padding:5px;
    border:1px solid darkgrey;
}
.btn {
    width:95%;
}
.btn:hover {
    background-color: #cad4f7 !important;
}
.card-body {
    padding:10px;
}
</style>
<br>
<div class="card" style="width:100%;margin:0; padding:0;" style="border:1px solid pink;">
    <div class="card-body" >
        <ul style="padding-left:5px">
<!--                <li><a type="button" class="btn btn-outline-primary bannerfont" href="{% url 'orchid_home' %}" style="font-size:16px;"><b>Enter OrchidRoots</b></a></li>-->
            <li class="li-side"><a type="button" class="btn sidebtn btn-outline-primary btn-sm bannerfont" href="{% url 'orchidlist:advanced' %}"><b>Advanced Search</b></a></li>
            <li class="li-side"><a type="button" class="btn sidebtn btn-outline-primary btn-sm" href="{% url 'documents:instructionupload' %}">Upload Guideline</a></li>
            <li class="li-side"><a type="button" class="btn sidebtn btn-outline-primary btn-sm" href="{% url 'donation:donateapp' %}">Donate</a></li>
            <li class="li-side"><a type="button" class="btn sidebtn btn-default btn-sm" href="{% url 'documents:photosubmissionguideline' %}">Photo submission</a></li>
            <li class="li-side"><a type="button" class="btn sidebtn btn-default btn-sm" href="{% url 'documents:changes' %}">Release history</a></li>
            <li class="li-side"><a type="button" class="btn sidebtn btn-default btn-sm" href="{% url 'documents:list' %}">Documentation</a></li>
            <li class="li-side"><a type="button" class="btn sidebtn btn-default btn-sm" href="{% url 'documents:privacy_policy' %}">Privacy policy</a></li>
            {% if user.tier.tier > 3 %}
                <li class="li-side"><a type="button" class="btn sidebtn btn-default btn-sm border" href="{% url 'documents:migration' %}">Deployment</a></li>
                <li class="li-side"><a type="button" class="btn sidebtn btn-default btn-sm border" href="{% url 'documents:future_development' %}">Future Development</a></li>
            {% endif %}
        </ul>
<hr>
        <ul style="padding-left:20px; font-size:13px;">
           <span style="font-size:16px;font-weight:600;">Other resources</span>
           <li class="li-side"><a href="https://http://apps.kew.org/wcsp/home.do" target="_blank">WCSP</a></li>
           <li class="li-side"><a href="https://www.ipni.org/" target="_blank">IPNI</a></li>
           <li class="li-side"><a href="http://apps.rhs.org.uk/horticulturaldatabase/orchidregister/orchidregister.asp" target="_blank">RHS</a></li>
           <li class="li-side"><a href="https://www.rhs.org.uk/about-the-rhs/publications/orchid-hybrid-lists" target="_blank">RHS Hybrid Lists</a></li>
           <li class="li-side"><a href="http://www.vdof.de/eng/descriptions.htm" target="_blank">Orchideen Journal</a></li>
           <li class="li-side"><a href="http://www.orchidsnewguinea.com/orchid-genera-and-species-list/" target="_blank">Orchids of New Guinea</a></li>
           <li class="li-side"><a href="https://orchid.unibas.ch/index.php/en/database-search/advanced-search" target="_blank">Unibas</a></li>
           <li class="li-side"><a href="http://legacy.tropicos.org/NameSearch.aspx" target="_blank">Tropicos</a></li>
           <li class="li-side"><a href="http://www.efloras.org/browse.aspx?flora_id=2&start_taxon_id=10638" target="_blank">Flora of China</a></li>
           <li class="li-side"><a href="http://www.orchidspecies.com/" target="_blank">IOSPE</a></li>
           <li class="li-side"><a href="https://www.uniprot.org/taxonomy/4747" target="_blank">UniProt</a></li>
           <li class="li-side"><a href="http://www.catalogueoflife.org/col/browse/tree/id/ca5523e7c617383a409f4179601ffa1c" target="_blank">Catalog of Life</a></li>
           <li class="li-side"><a href="https://itol.embl.de/itol.cgi" target="_blank">iTOL Tree of Life</a></li>
           <li class="li-side"><a href="https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?id=4747" target="_blank">NCBI Taxonomy Browser</a></li>
           <li class="li-side"><a href="http://powo.science.kew.org/" target="_blank">Kewscience Plants of the World</a></li>

        </ul>
    </div>
</div>