detail/urls.py
from django.urls import path
from . import views

# TODO: Add a new page: Compare two species/hybrids
# TODO: Add feature search page - search by color, features
# TODO: Add search by ancestors pair.
# TODO: Add search by location

app_name = 'detail'
urlpatterns = [
    # detail
    # path('selectspecies/<int:pid>/', views.selectspecies, name='selectspecies'),
    # path('nav/', views.nav, name='nav'),
    path('species/', views.information, name='information'),
    path('species/<int:pid>/', views.information, name='information'),
    path('hybrid/', views.information, name='information'),
    path('hybrid/<int:pid>/', views.information, name='information'),
    path('<int:pid>/species/', views.information, name='information'),
    path('<int:pid>/species_detail/', views.information, name='information'),
    path('<int:pid>/hybrid/', views.information, name='information'),
    path('<int:pid>/hybrid_detail/', views.information, name='information'),
    path('compare/<int:pid>/', views.compare, name='compare'),
    path('compare/', views.compare, name='compare'),
    path('createhybrid/', views.createhybrid, name='createhybrid'),
    path('information/<int:pid>/', views.information, name='information'),
    path('information/', views.information, name='information'),

    path('ancestor/', views.ancestor, name='ancestor'),
    path('ancestor/<int:pid>/', views.ancestor, name='ancestor'),
    path('ancestrytree/<int:pid>/', views.ancestrytree, name='ancestrytree'),
    path('ancestrytree/', views.ancestrytree, name='ancestrytree'),
    path('progeny/<int:pid>/', views.progeny, name='progeny'),
    path('progenyimg/<int:pid>/', views.progenyimg, name='progenyimg'),

    path('comment/', views.comment, name='comment'),
    path('comments/', views.comments, name='comments'),
    path('myphoto/<int:pid>/', views.myphoto, name='myphoto'),
    path('myphoto/', views.myphoto, name='myphoto'),
    path('myphoto_browse_spc/', views.myphoto_browse_spc, name='myphoto_browse_spc'),
    path('myphoto_browse_hyb/', views.myphoto_browse_hyb, name='myphoto_browse_hyb'),
    path('curate/<int:pid>/', views.curate, name='curate'),
    path('<int:pid>/photos/', views.photos, name='photos'),
    path('photos/<int:pid>/', views.photos, name='photos'),
    path('curateinfospc/<int:pid>/', views.curateinfospc, name='curateinfospc'),
    path('curateinfospc/', views.curateinfospc, name='curateinfospc'),
    path('curateinfohyb/<int:pid>/', views.curateinfohyb, name='curateinfohyb'),
    path('curateinfohyb/', views.curateinfohyb, name='curateinfohyb'),
    path('curate_newupload/', views.curate_newupload, name='curate_newupload'),
    path('curate_pending/', views.curate_pending, name='curate_pending'),
    path('curate_newapproved/', views.curate_newapproved, name='curate_newapproved'),
    path('reidentify/<int:orid>/<int:pid>/', views.reidentify, name='reidentify'),

    path('uploadfile/<int:pid>/', views.uploadfile, name='uploadfile'),
    path('uploadweb/<int:pid>/', views.uploadweb, name='uploadweb'),
    path('uploadweb/<int:pid>/<int:orid>/', views.uploadweb, name='uploadweb'),
    path('deletephoto/<int:orid>/', views.deletephoto, name='deletephoto'),
    path('deletewebphoto/<int:pid>/', views.deletewebphoto, name='deletewebphoto'),
    path('approvemediaphoto/<int:pid>/', views.approvemediaphoto, name='approvemediaphoto'),
]

myproject/urls.py
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.generic import TemplateView
from django.views.generic.base import TemplateView
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from accounts.views import  user_reset_password, login_page, register_page, UpdateProfileView, SetEmailView,\
    ChangeEmailView, PasswordChangeRedirect, CustomPasswordResetFromKeyView
from myproject.views import orchid_home
from myproject.views import robots_txt

urlpatterns = [
    path('admin/', admin.site.urls),
    # path("robots.txt", robots_txt),
    path("robots.txt", TemplateView.as_view(template_name="robots.txt", content_type="text/plain"),
    path('', orchid_home, name='orchid_home'),

    path('login/', login_page, name='login'),
    path('register/', register_page, name='register'),
    path('set_email/', SetEmailView.as_view(), name='set_email'),
    path('change_email/', ChangeEmailView.as_view(), name='change_email'),
    path('update_profile/', UpdateProfileView.as_view(), name='update_profile'),
    path('logout/', LogoutView.as_view(), {'next_page': '//'}, name='logout'),
    path('accounts/password/change/', PasswordChangeRedirect.as_view(), name="account_password_change"),
    
    path('accounts/password/user_reset_password/', user_reset_password, name="user_account_reset_password"),
    re_path(
        r"^accounts/password/reset/key/(?P<uidb36>[0-9A-Za-z]+)-(?P<key>.+)/$",
        CustomPasswordResetFromKeyView.as_view(),
        name="account_reset_password_from_key",
    ),
    path('accounts/', include('allauth.urls')),
    # path('password_reset/', include(password_reset.urls)),

    path('search/', include('search.urls')),
    path('orchidlist/', include('orchidlist.urls')),
    path('detail/', include('detail.urls')),
    path('documents/', include('documents.urls')),
    path('donation/', include('donation.urls')),

    # old
    path('natural/', include('natural.urls')),
    path('orchid/', include('orchid.urls')),
    path('orchidlite/', include('orchidlite.urls')),

    # path('sendmail/', include('sendmail.urls')),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

orchidlist/urls.py
# from django.conf.urls import url, include
from django.urls import path
from . import views

# TODO: Add a new page: Compare two species/hybrids
# TODO: Add feature search page - search by color, features
# TODO: Add search by ancestors pair.
# TODO: Add search by location

app_name = 'orchidlist'
urlpatterns = [
    # Lists
    path('family/', views.family, name='family'),
    path('subfamily/', views.subfamily, name='subfamily'),
    path('tribe/', views.tribe, name='tribe'),
    path('subtribe/', views.subtribe, name='subtribe'),
    path('genera/', views.genera, name='genera'),
    path('species/', views.species_list, name='species'),
    path('hybrid/', views.hybrid_list, name='hybrid'),
    path('progeny/<int:pid>/', views.progeny, name='progeny'),
    path('progeny/', views.progeny, name='progeny'),
    path('progenyimg/<int:pid>/', views.progenyimg, name='progenyimg'),
    path('progenyimg/', views.progenyimg, name='progenyimg'),
    path('subgenus/', views.subgenus, name='subgenus'),
    path('section/', views.section, name='section'),
    path('subsection/', views.subsection, name='subsection'),
    path('series/', views.series, name='series'),
    path('advanced/', views.advanced, name='advanced'),
    path('browsegen/', views.browsegen, name='browsegen'),
    path('browse/', views.browse, name='browse'),
    path('browsedist/', views.browsedist, name='browsedist'),

    # Legacy urls
]

accounts/models.py
from allauth.account.utils import perform_login
from allauth.exceptions import ImmediateHttpResponse
from allauth.socialaccount.signals import pre_social_login
from django.db import models
from django.conf import settings
from django.shortcuts import redirect
from django.db.models.signals import post_save
from allauth.account.signals import user_signed_up, user_logged_in, email_confirmed
from allauth.account.models import EmailAddress

from django.dispatch import receiver

from django.contrib.auth.models import (
    BaseUserManager, AbstractBaseUser
)
# import uuid


class BaseModel(models.Model):
    # uuid = models.UUIDField(primary_key=True, editable=False, default=uuid.uuid4)

    class Meta:
        abstract = True

class Tier(BaseModel):
    tier        = models.IntegerField(primary_key=True)
    max_upload  = models.IntegerField(default=0)
    description = models.CharField(max_length=150, null=True, blank=True)
    def __str__(self):
        return str(self.max_upload)


class UserManager(BaseUserManager):
    def create_user(self, username, email, password=None, fullname=None, credited_name=None, is_staff=False, is_admin=False, is_active=True):
        if not username:
            raise ValueError("User must have user name")
        if not email:
            raise ValueError("User must have email address")
        if not password:
            raise ValueError("User must have a password")
        user_obj = self.model(
            username = username,
            email = self.normalize_email(email),
            fullname = fullname,
            credited_name = credited_name,
        )
        user_obj.set_password(password)
        user_obj.staff = is_staff
        user_obj.admin = is_admin
        user_obj.active = is_active
        user_obj.save(using=self._db)
        return user_obj

    def create_staffuser(self, username, password=None):
        email = None
        user_obj = self.create_user(
            username,
            email,
            password=password,
            is_staff=True
        )
        return user_obj

    def create_superuser(self, username, email, password=None):
        user_obj = self.create_user(
            username,
            email,
            password=password,
            is_staff=True,
            is_admin=True
        )
        return user_obj


class User(AbstractBaseUser):
    username = models.CharField(max_length=255, unique=True)
    fullname = models.CharField(max_length=255, null=True)
    email = models.EmailField(verbose_name='email address', max_length=255, null=True,default=None, unique=True,)
    active = models.BooleanField(default=True) # Note, can use user.active
    is_active = models.BooleanField(default=True)
    staff = models.BooleanField(default=False) # a admin user; non super-user can use user.is_staff
    admin = models.BooleanField(default=False) # a superuser can use user.is_superuser
    created_date = models.DateTimeField(auto_now_add=True) # can use user.date_joined
    tier = models.ForeignKey(Tier, null=True, db_column='tier',on_delete=models.SET_NULL)

    credited_name =  models.CharField(max_length=255, null=True)
    specialty =  models.CharField(max_length=255, null=True)
    objects = UserManager()

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email'] # Username, Email & Password are required by default.

    def save(self, *args, **kwargs):
        if not self.tier:
            tier = Tier.objects.filter(tier=1).last()
            self.tier = tier
        return super().save(*args, **kwargs)

    def get_email(self):
        return self.email

    def get_short_name(self):
        # The user is identified by their email address
        return self.username

    def __str__(self):
        return self.username

    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True

    @property
    def is_staff(self): # FIXME: is_staff is a lookup field, it should not be overiden
        "Is the user a member of staff?"
        return self.staff

    @property
    def is_admin(self): # FIXME: is_admin is a lookup field, it should not be overiden
        "Is the user a admin member?"
        return self.admin

    # @property
    # def is_active(self): # is_active is a django auth special lookup field should not be overiden
    #     "Is the user active?"
    #     return self.active

    def get_author(self):
        author = Profile.objects.get(user_id=self.id)
        return author.current_credit_name

    def add_email_address(self, request, new_email):
        # Add a new email address for the user, and send email confirmation.
        # Old email will remain the primary until the new one is confirmed.
        return EmailAddress.objects.add_email(request, self.user, new_email, confirm=True)

    
@receiver(email_confirmed)
def update_user_email(sender, request, email_address, **kwargs):
    # Once the email address is confirmed, make new email_address primary.
    # This also sets user.email to the new email address.
    # email_address is an instance of allauth.account.models.EmailAddress
    email_address.set_as_primary()
    # Get rid of old email addresses
    stale_addresses = EmailAddress.objects.filter(
        user=email_address.user).exclude(primary=True).delete()
        
class Country(BaseModel):
    # class Meta:
    #     unique_together = (("dist_code", "dist_num", "region"),)
    #     ordering = ['country','region']
    dist_code = models.CharField(max_length=3,primary_key=True)
    dist_num  = models.IntegerField(null=True, blank=True)
    country   = models.CharField(max_length=100, null=True, blank=True)
    region    = models.CharField(max_length=100, null=True, blank=True)
    orig_code = models.CharField(max_length=100, null=True, blank=True)
    uncertainty = models.CharField(max_length=10, null=True, blank=True)
    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return '%s' % self.country


class Photographer(BaseModel):
    author_id = models.CharField(max_length=50, primary_key=True)
    displayname = models.CharField(max_length=50)
    fullname = models.CharField(max_length=50)
    affiliation = models.CharField(max_length=200, null=True, blank=True)
    url = models.CharField(max_length=400, null=True, blank=True)
    web = models.CharField(max_length=400, null=True, blank=True)
    status = models.CharField(max_length=10, default='TBD')
    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)
    expertise = models.CharField(max_length=500, null=True)
    # user_id   = models.OneToOneField(User,unique=True, null=True, blank=True, db_column='user_id', related_name='userid', on_delete=models.SET_NULL)
    user_id   =  models.OneToOneField(
        User,
        db_column='user_id',
        null = True,
        on_delete=models.SET_NULL)
        # models.ForeignKey(User, null=True, blank=True, db_column='user_id', related_name='userid', on_delete=models.SET_NULL)

    def get_authid(self):
        return self.author_id

    def __str__(self):
        if self.displayname != self.fullname:
            return '%s (%s)' % (self.displayname, self.fullname)
        return self.fullname

    # def mypriphoto (self):
    #     myimg = SpcImages.objects.filter(rank__gt=0).filter(user_id=self.user_id).count() + \
    #             SpcImages.objects.filter(rank__gt=0).filter(user_id=self.user_id).count() + \
    #             UploadFile.objects.filter(user_id=self.user_id).count()
    #     return '%' % str(myimg)


class Profile(BaseModel):
    user = models.OneToOneField(User, primary_key=True,on_delete=models.CASCADE)
    # fullname = models.CharField(max_length=255,blank=True,null=True)
    confirm_email = models.CharField(max_length=100, blank=True)
    photo_credit_name = models.CharField(max_length=100, blank=True)
    current_credit_name = models.OneToOneField(Photographer, blank=True, null=True, on_delete=models.SET_NULL)
    specialty = models.CharField(max_length=500, null=True, blank=True)
    portfolio_site = models.URLField(max_length=500, blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics', null=True, blank=True)
    profile_pic_url = models.URLField(null=True, blank=True)
    # country = models.CharField(max_length=10, null=True, blank=True)
    country = models.ForeignKey(Country, db_column='country', on_delete=models.SET_NULL, null=True, blank=True)
    approved = models.BooleanField( blank=True, default=True)
    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)
    def __str__(self):
        if self.user.fullname:
            return self.user.fullname
        else:
            return self.user.username


class Donation(BaseModel):
    stripe_charge_id = models.CharField(max_length=50)
    user = models.ForeignKey(User, blank=True, null=True, on_delete=models.SET_NULL)
    amount = models.FloatField()
    payment_type = models.CharField(max_length=20,blank=True,null=True)
    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.user.username


class Partner(BaseModel):
    partner_id = models.CharField(max_length=50, primary_key=True)
    author = models.ForeignKey(Photographer, db_column='author', on_delete=models.SET_NULL, null=True, blank=True)
    displayname = models.CharField(max_length=50)
    fullname = models.CharField(max_length=50)
    logo = models.CharField(max_length=50, blank=True)
    banner = models.CharField(max_length=50, blank=True)

detail/models.py
from django.db import models

# Create your models here.

detail/templates/detail/curate_home.html
{% load static %}
{% include "base.html" %}
{% include "detail/detail-title.html" %}
{% block body %}
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'utils/css/lightbox.css' %}">
    <script type="text/javascript" src="{% static 'utils/js/lightbox.js' %}"></script>
</head>





{% endblock %}

detail/templates/detail/curate_newupload.html
{% load static %}
{% include "base.html" %}
{% include "detail/detail-title.html" %}
{% block body %}
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'utils/css/lightbox.css' %}">
    <script type="text/javascript" src="{% static 'utils/js/lightbox.js' %}"></script>
</head>

<style>
    .mybtn {
        font-size:13px;
        width:200px;
        background-color: white;
        border: 1px solid grey;
        margin: 3px;
    }
    .mymenu {
        max-height:400px;
        overflow-y: auto;
        font-size:12px;
    }
.thumbnails {
   object-fit: cover;
   overflow: hidden;
   height: 12vw;
   width : 12vw;
   padding:2px 1px 3px 1px;
}

div.text-c {
    position: absolute;
    top: 80%;
    left: 50%;
    transform: translate(-50%, -50%);
    font-size: 13px;
}

.left-p {
    width:100%;
    min-width:200px;
    border: 0 solid lightgrey;
    max-height:600px;
    font-size: 13px;
    overflow-y:auto;
}

@media only screen and (max-width: 830px) {
    .left-p {
        width:100%;
        min-width:80px;
        max-height:400px;
        font-size: 12px;
        overflow-y:auto;
    }

    div.text-c {
        font-size: 10px;
    }
    .thumbnails {
       height: 22vw;
       width : 22vw;
       padding:2px 1px 3px 1px;
    }
}

@media only screen and (max-width: 580px) {
}

.box {
    position: relative;
    display: inline-block;
    text-align: center;
    color: white;
    margin: 0;
}

img{
    width:100%;
}

.mybtn{
    border:1px solid lightblue;
    font-size:13px;
    height:30px;
}
</style>
<div style="width:95%;margin:0 auto;">
    {% include "detail/detail-nav.html" %}

    <div class="tab-content clearfix" style="background-color: white; margin:0 auto;border-left:1px solid lightgrey;border-right:1px solid lightgrey;border-bottom:1px solid lightgrey;">
        <div class="d-flex flex-row bd-highlight mb-3">
            <div class="p-2" style="width:100%">
                <div style="margin:0 auto; text-align: center;min-height:200px;">
                    <br>
                    <br>
                    {% if file_list %}
                        {% if last_page > 1 %}
                            {% include "detail/paginator_upl.html" %}
                        {% endif %}
                        {% for image in file_list %}
                            <div style="display:inline-block">
                                <a href="{% static 'media/' %}{{image.image_file_path}}" data-lightbox="uploadfile">
                                        <img class="thumbnails" alt="" src="{% static 'media/' %}{{image.image_file_path}}">
                                </a>
                                <div style="font-size:12px">
                                    <a href="{% url 'detail:photos' image.pid_id %}?&id={{image.id}}&tab=sum&gen={{species.gen.pid}}&action=file">{{image.pid.namecasual|safe}}</a>
                                    <br>{{image.created_date.date}}
                                    <br>
                                    {% if image.approved %}
                                        <b>Approved</b>
                                    {% else %}
                                        <a href="{% url 'detail:approvemediaphoto' image.pid_id %}?&id={{image.id}}&tab=sum&gen={{species.gen.pid}}">Approve</a>
                                    {% endif %}
                                    <a href="{% url 'detail:deletephoto' image.id %}?pid={{image.pid_id}}&role={{role}}&tab={{tab}}&page={{page}}&area=curate_newupload" >Delete</a>
                                </div>
                            </div>
                        {% endfor %}
                    {% else %}
                        <span style="font-size:12px;">
                        None
                        </span>
                    {% endif %}
                </div>
            </div>
        </div>
        <br>
    </div>
</div>




{% endblock %}

detail/templates/detail/private-nav.html
<style>
    .nav-tabs {
        font-size:13px;
    }
    @media only screen and (max-width: 500px) {
        .nav-tabs {
            font-size:9px
        }
        .nav-item {
            width:70px;
            /*min-height:70px;*/
        }

    }


</style>



<div style="font-size: 13px;width:100%;margin:0;padding:0;">

    <div class="nav nav-tabs">
        <ul class="nav nav-tabs navbar-expand-lg" >
        {% if brwspc == 'active' %}
            <li class="nav-item"><div class="nav-link active"><span style="color:#575757;">My Species</span></div></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'detail:myphoto_browse_hyb' %}?role=pri&tab=brwhyb&author={{author.author_id}}"><span style="color:#575757;">My Hybrid</span></a></li>
        {% elif brwhyb == 'active' %}
            <li class="nav-item"><a class="nav-link" href="{% url 'detail:myphoto_browse_spc' %}?role=pri&tab=brwspc&author={{author.author_id}}"><span style="color:#575757;">My Species</span></a></li>
            <li class="nav-item"><div class="nav-link active"><span style="color:#575757;">My Hybrid</span></div></li>
        {% else %}
            <li class="nav-item"><a class="nav-link" href="{% url 'detail:myphoto_browse_spc'  %}?role=pri&tab=brwspc&author={{author.author_id}}"><span style="color:#575757;">My Species</span></a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'detail:myphoto_browse_hyb'  %}?role=pri&tab=brwhyb&author={{author.author_id}}"><span style="color:#575757;">My Hybrid</span></a></li>
            {% if species.pid > 0 %}
    <!--                If pid in request, can upload and update species info-->
                {% if species.pid %}
                    <li class="nav-item"><a class="nav-link {{pri}}" href="{% url 'detail:myphoto' species.pid %}?role=pri&tab=pri&gen={{species.gen.pid}}&author={{author.author_id}}"><span style="color:#575757;">Detail</span></a></li>
<!--                    <li class="nav-item"><a class="nav-link {{loc}}" href="{% url 'detail:uploadfile' species.pid %}?role=pri&tab=loc&author={{author.author_id}}"><span style="color:#575757;">upload file</span></a></li>-->
                    <li class="nav-item dropdown">
                        <a class="nav-link {{loc}} dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Upload</a>
                        <div class="dropdown-menu">
<!--                            <a class="dropdown-item" href="{% url 'detail:uploadweb' species.pid %}?role=pri&tab=loc&author={{author.author_id}}"><span style="color:#575757;">upload url</span></a>-->
                            <a class="dropdown-item" href="{% url 'detail:uploadfile' species.pid %}?role=pri&tab=loc&author={{author.author_id}}"><span style="color:#575757;">upload file</span></a>
                        </div>
                    </li>
                {% else %}
    <!--                If comes from page with no PID-->
                    <li class="nav-item"><a class="nav-link" href="{% url 'detail:myphoto' 0 %}?role=pri&tab=sum&gen={{species.gen.pid}}&pid={{species.pid}}"><span style="color:#575757;">Detail</span></a></li>
<!--                    <li class="nav-item"><a class="nav-link active" href="{% url 'detail:uploadweb' 0 %}?role=pri&tab=web"><span style="color:#575757;">upload url</span></a></li>-->
                    <li class="nav-item"><a class="nav-link " href="{% url 'detail:uploadfile' 0 %}?role=pri&tab=loc"><span style="color:#575757;">upload file</span></a></li>

                {% endif %}
            {% endif %}
        {% endif %}


        </ul>
    </div>
</div>

detail/templates/detail/uploadfile.html
{% load static %}
{% include "base.html" %}
{% load crispy_forms_tags %}
{% include "detail/detail-title.html" %}
{% block body %}
{{ form.media.css }}
{{ form.media.js }}
    <!--Main sections-->
<style>
    .django-select2 {
        width: 300px;
    }
</style>

<div style="width:95%;margin:0 auto;padding:0;">
             <!--main section-->
    {% include 'detail/detail-nav.html' %}
    <br>
    {% if myphotos > user.tier.max_upload %}
        <div class="container">
            <br><br>
            <h5><small>You have exceeded the number of allowed uploads for this species.  You must delete some of your private photos before adding a new one.</small></h5>
        </div>
    {% else %}
        <div class="tab-content clearfix" style="width:100%;background-color:white;margin:0 auto;border-left:0 solid lightgrey;border-right:0 solid lightgrey;border-bottom:1px solid lightgrey">
            <div class="container" style="width:90%;font-size:13px;">
                <form method="post" action="{% url 'detail:uploadfile' species.pid %}" enctype="multipart/form-data">
                    {% csrf_token %}
                        <input type="hidden" name="role" value="{{role}}" />
                        <button type="submit" class="btn btn-primary btn-sm"  style="width:80px">Save</button>
                        <a href="{% url 'detail:photos' species.pid %}?role={{role}}"> &nbsp;&nbsp;&nbsp;Cancel</a>
                        {{form.author|as_crispy_field}}
                        {{form.originator|as_crispy_field}}

        <!--                <hr  class="my-4">-->
                        <div class="form-row">
                            <div class="form-group col-md-6 mb-0">
                               <br><h5>{{species.name|safe}}</h5>
                            </div>
                            <div class="form-group col-md-6 mb-0">
                                {{form.image_file_path|as_crispy_field}}
                            </div>
                        </div>

                        <div class="form-row">
                            <div class="form-group col-md-6 mb-0">
                                 {{form.variation|as_crispy_field}}
                            </div>
                            <div class="form-group col-md-6 mb-0">
                                {{form.forma|as_crispy_field}}
                            </div>
                        </div>

                        <div class="form-row">
                            <div class="form-group col-md-4 mb-0">
                                {{form.name|as_crispy_field}}
                            </div>
                            <div class="form-group col-md-4 mb-0">
                                 {{form.awards|as_crispy_field}}
                            </div>
                            <div class="form-group col-md-4 mb-0">
                                {{form.location|as_crispy_field}}
                            </div>
                         </div>

                        {{form.description|as_crispy_field}}
                        {{form.text_data|as_crispy_field}}
                        <button type="submit" class="btn btn-primary btn-sm"  style="width:80px">Save</button>
                        <a href="{% url 'detail:photos' species.pid %}?role={{role}}"> &nbsp;&nbsp;&nbsp;Cancel</a>

                        {% if redirect_field_value %}
                           <input type="hidden" name="{{ redirect_field_name }}" value="{{ redirect_field_value }}" />
                           <input type="hidden" name="role" value="{{ role }}" />
                        {% endif %}
                    </form>
                </div>
            </div>
    {% endif %}
</div>
<script>
$(document).ready(function(){
  $('[data-toggle="tooltip"]').tooltip();
});
$(document).ready(function() {
    $("#id_author").select2();
});

</script>
{% endblock %}