detail/urls.py
from django.urls import path
from . import views

# TODO: Add a new page: Compare two species/hybrids
# TODO: Add feature search page - search by color, features
# TODO: Add search by ancestors pair.
# TODO: Add search by location

app_name = 'detail'
urlpatterns = [
    # detail
    # path('selectspecies/<int:pid>/', views.selectspecies, name='selectspecies'),
    # path('nav/', views.nav, name='nav'),
    path('species/', views.information, name='information'),
    path('species/<int:pid>/', views.information, name='information'),
    path('hybrid/', views.information, name='information'),
    path('hybrid/<int:pid>/', views.information, name='information'),
    path('<int:pid>/species/', views.information, name='information'),
    path('<int:pid>/species_detail/', views.information, name='information'),
    path('<int:pid>/hybrid/', views.information, name='information'),
    path('<int:pid>/hybrid_detail/', views.information, name='information'),
    path('compare/<int:pid>/', views.compare, name='compare'),
    path('compare/', views.compare, name='compare'),
    path('createhybrid/', views.createhybrid, name='createhybrid'),
    path('information/<int:pid>/', views.information, name='information'),
    path('information/', views.information, name='information'),

    path('ancestor/', views.ancestor, name='ancestor'),
    path('ancestor/<int:pid>/', views.ancestor, name='ancestor'),
    path('ancestrytree/<int:pid>/', views.ancestrytree, name='ancestrytree'),
    path('ancestrytree/', views.ancestrytree, name='ancestrytree'),
    path('progeny/<int:pid>/', views.progeny, name='progeny'),
    path('progenyimg/<int:pid>/', views.progenyimg, name='progenyimg'),

    path('comment/', views.comment, name='comment'),
    path('comments/', views.comments, name='comments'),
    path('myphoto/<int:pid>/', views.myphoto, name='myphoto'),
    path('myphoto/', views.myphoto, name='myphoto'),
    path('myphoto_browse_spc/', views.myphoto_browse_spc, name='myphoto_browse_spc'),
    path('myphoto_browse_hyb/', views.myphoto_browse_hyb, name='myphoto_browse_hyb'),
    path('curate/<int:pid>/', views.curate, name='curate'),
    path('<int:pid>/photos/', views.photos, name='photos'),
    path('photos/<int:pid>/', views.photos, name='photos'),
    path('curateinfospc/<int:pid>/', views.curateinfospc, name='curateinfospc'),
    path('curateinfospc/', views.curateinfospc, name='curateinfospc'),
    path('curateinfohyb/<int:pid>/', views.curateinfohyb, name='curateinfohyb'),
    path('curateinfohyb/', views.curateinfohyb, name='curateinfohyb'),
    path('curate_newupload/', views.curate_newupload, name='curate_newupload'),
    path('curate_pending/', views.curate_pending, name='curate_pending'),
    path('curate_newapproved/', views.curate_newapproved, name='curate_newapproved'),
    path('reidentify/<int:orid>/<int:pid>/', views.reidentify, name='reidentify'),

    path('uploadfile/<int:pid>/', views.uploadfile, name='uploadfile'),
    path('uploadweb/<int:pid>/', views.uploadweb, name='uploadweb'),
    path('uploadweb/<int:pid>/<int:orid>/', views.uploadweb, name='uploadweb'),
    path('deletephoto/<int:orid>/', views.deletephoto, name='deletephoto'),
    path('deletewebphoto/<int:pid>/', views.deletewebphoto, name='deletewebphoto'),
    path('approvemediaphoto/<int:pid>/', views.approvemediaphoto, name='approvemediaphoto'),
]

myproject/urls.py
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.generic import TemplateView
from django.views.generic.base import TemplateView
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from accounts.views import  user_reset_password, login_page, register_page, UpdateProfileView, SetEmailView,\
    ChangeEmailView, PasswordChangeRedirect, CustomPasswordResetFromKeyView
from myproject.views import orchid_home
from myproject.views import robots_txt

urlpatterns = [
    path('admin/', admin.site.urls),
    # path("robots.txt", robots_txt),
    path("robots.txt", TemplateView.as_view(template_name="robots.txt", content_type="text/plain"),
    path('', orchid_home, name='orchid_home'),

    path('login/', login_page, name='login'),
    path('register/', register_page, name='register'),
    path('set_email/', SetEmailView.as_view(), name='set_email'),
    path('change_email/', ChangeEmailView.as_view(), name='change_email'),
    path('update_profile/', UpdateProfileView.as_view(), name='update_profile'),
    path('logout/', LogoutView.as_view(), {'next_page': '//'}, name='logout'),
    path('accounts/password/change/', PasswordChangeRedirect.as_view(), name="account_password_change"),
    
    path('accounts/password/user_reset_password/', user_reset_password, name="user_account_reset_password"),
    re_path(
        r"^accounts/password/reset/key/(?P<uidb36>[0-9A-Za-z]+)-(?P<key>.+)/$",
        CustomPasswordResetFromKeyView.as_view(),
        name="account_reset_password_from_key",
    ),
    path('accounts/', include('allauth.urls')),
    # path('password_reset/', include(password_reset.urls)),

    path('search/', include('search.urls')),
    path('orchidlist/', include('orchidlist.urls')),
    path('detail/', include('detail.urls')),
    path('documents/', include('documents.urls')),
    path('donation/', include('donation.urls')),

    # old
    path('natural/', include('natural.urls')),
    path('orchid/', include('orchid.urls')),
    path('orchidlite/', include('orchidlite.urls')),

    # path('sendmail/', include('sendmail.urls')),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

orchidlist/urls.py
# from django.conf.urls import url, include
from django.urls import path
from . import views

# TODO: Add a new page: Compare two species/hybrids
# TODO: Add feature search page - search by color, features
# TODO: Add search by ancestors pair.
# TODO: Add search by location

app_name = 'orchidlist'
urlpatterns = [
    # Lists
    path('family/', views.family, name='family'),
    path('subfamily/', views.subfamily, name='subfamily'),
    path('tribe/', views.tribe, name='tribe'),
    path('subtribe/', views.subtribe, name='subtribe'),
    path('genera/', views.genera, name='genera'),
    path('species/', views.species_list, name='species'),
    path('hybrid/', views.hybrid_list, name='hybrid'),
    path('progeny/<int:pid>/', views.progeny, name='progeny'),
    path('progeny/', views.progeny, name='progeny'),
    path('progenyimg/<int:pid>/', views.progenyimg, name='progenyimg'),
    path('progenyimg/', views.progenyimg, name='progenyimg'),
    path('subgenus/', views.subgenus, name='subgenus'),
    path('section/', views.section, name='section'),
    path('subsection/', views.subsection, name='subsection'),
    path('series/', views.series, name='series'),
    path('advanced/', views.advanced, name='advanced'),
    path('browsegen/', views.browsegen, name='browsegen'),
    path('browse/', views.browse, name='browse'),
    path('browsedist/', views.browsedist, name='browsedist'),

    # Legacy urls
]

orchidlist/models.py
from django.db import models

# Create your models here.

orchidlist/views.py
from django.shortcuts import render
from django.db.models import Q
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.views.decorators.http import require_GET
import string
from itertools import chain
from utils.views import write_output, getRole
import logging
import random
logger = logging.getLogger(__name__)

# Create your views here.
from django.apps import apps
Genus = apps.get_model('orchiddb', 'Genus')
GenusRelation = apps.get_model('orchiddb', 'GenusRelation')
Genusacc = apps.get_model('orchiddb', 'Genusacc')
Intragen = apps.get_model('orchiddb', 'Intragen')
Species = apps.get_model('orchiddb', 'Species')
Hybrid = apps.get_model('orchiddb', 'Hybrid')
Accepted = apps.get_model('orchiddb', 'Accepted')

Subgenus = apps.get_model('orchiddb', 'Subgenus')
Section = apps.get_model('orchiddb', 'Section')
Subsection = apps.get_model('orchiddb', 'Subsection')
Series = apps.get_model('orchiddb', 'Series')

# Infragen = apps.get_model('orchiddb', 'Infragen')
Family = apps.get_model('orchiddb', 'Family')
Subfamily = apps.get_model('orchiddb', 'Subfamily')
Tribe = apps.get_model('orchiddb', 'Tribe')
Subtribe = apps.get_model('orchiddb', 'Subtribe')
Distribution = apps.get_model('orchiddb', 'Distribution')
Region = apps.get_model('orchiddb', 'Region')
Subregion = apps.get_model('orchiddb', 'Subregion')
Localregion = apps.get_model('orchiddb', 'Localregion')
GeoLoc = apps.get_model('orchiddb', 'GeoLoc')
SpcImages = apps.get_model('orchiddb', 'SpcImages')
HybImages = apps.get_model('orchiddb', 'HybImages')
UploadFile = apps.get_model('orchiddb', 'UploadFile')
AncestorDescendant = apps.get_model('orchiddb', 'AncestorDescendant')
User = get_user_model()
alpha_list = string.ascii_uppercase

#
# @require_GET
# def robots_txt(request):
#     lines = [
#         "User-Agent: *",
#         "Disallow: /orchidlist/",
#     ]
#     return HttpResponse("\n".join(lines), content_type="text/plain")


# High level lists
def family(request):
    # -- List Genuses
    family_list = Family.objects.order_by('family')
    context = {'family_list': family_list, 'alpha_list': alpha_list, 'title': 'families', }
    return render(request, 'orchidlist/family.html', context)


def subfamily(request):
    # -- List Genuses
    subfamily_list = Subfamily.objects.order_by('subfamily')
    context = {'subfamily_list': subfamily_list, 'alpha_list': alpha_list, 'title': 'subfamilies', }
    return render(request, 'orchidlist/subfamily.html', context)


def tribe(request):
    sf = ''
    sf_list = Subfamily.objects.all()
    tribe_list = Tribe.objects.order_by('tribe')
    if 'sf' in request.GET:
        sf = request.GET['sf']
        if sf:
            sf_obj = Subfamily.objects.get(pk=sf)
            if sf_obj:
                tribe_list = tribe_list.filter(subfamily=sf)
    context = {'tribe_list': tribe_list, 'title': 'tribes', 'sf': sf, 'sf_list': sf_list, }
    return render(request, 'orchidlist/tribe.html', context)


def subtribe(request):
    subtribe_list = Subtribe.objects.all().order_by('subtribe')
    sf = ''
    t = ''
    sf_list = Subfamily.objects.all()
    t_list = Tribe.objects.all()
    if 'sf' in request.GET:
        sf = request.GET['sf']
        if sf:
            sf_obj = Subfamily.objects.get(pk=sf)
            if sf_obj:
                subtribe_list = subtribe_list.filter(subfamily=sf)
    if 't' in request.GET:
        t = request.GET['t']
        if t:
            t_obj = Tribe.objects.get(pk=t)
            if t_obj:
                subtribe_list = subtribe_list.filter(tribe=t)

    context = {'subtribe_list': subtribe_list, 'title': 'subtribes', 't': t, 'sf': sf, 'sf_list': sf_list,
               't_list': t_list, }
    return render(request, 'orchidlist/subtribe.html', context)


@login_required
def advanced(request):
    sf = t = st = ''
    specieslist = []
    hybridlist = []
    intragen_list = []

    subfamily_list = Subfamily.objects.all()
    if 'sf' in request.GET:
        sf = request.GET['sf']
    if sf:
        tribe_list = Tribe.objects.filter(subfamily=sf)
    else:
        tribe_list = Tribe.objects.all()
    if 't' in request.GET:
        t = request.GET['t']
    if t:
        subtribe_list = Subtribe.objects.filter(tribe=t)
    else:
        subtribe_list = Subtribe.objects.all()
    if 'st' in request.GET:
        st = request.GET['st']

    genus_list = Genus.objects.filter(cit_status__isnull=True).exclude(cit_status__exact='').order_by('genus')

    if 'role' in request.GET:
        role = request.GET['role']
    else:
        role = 'pub'

    if 'genus' in request.GET:
        genus = request.GET['genus']
        if genus:
            try:
                genus = Genus.objects.get(genus=genus)
            except Genus.DoesNotExist:
                genus = ''
    else:
        genus = ''

    if genus:
        # new genus has been selected. Now select new species/hybrid
        specieslist = Species.objects.filter(gen=genus.pid).filter(type='species').filter(
                cit_status__isnull=True).exclude(cit_status__exact='').order_by('species', 'infraspe', 'infraspr')

        hybridlist = Species.objects.filter(gen=genus.pid).filter(type='hybrid').order_by('species')

        # Construct intragen list
        if genus.type == 'hybrid':
            parents = GenusRelation.objects.get(gen=genus.pid)
            if parents:
                parents = parents.parentlist.split('|')
                intragen_list = Genus.objects.filter(pid__in=parents)
        else:
            intragen_list = Genus.objects.filter(description__icontains=genus).filter(type='hybrid').filter(
                num_hybrid__gt=0)

    write_output(request, str(genus))
    context = {
        'genus': genus, 'genus_list': genus_list,
        'species_list': specieslist, 'hybrid_list': hybridlist, 'intragen_list': intragen_list,
        'subfamily': sf, 'tribe': t, 'subtribe': st,
        'subfamily_list': subfamily_list, 'tribe_list': tribe_list, 'subtribe_list': subtribe_list,
        'level': 'search', 'title': 'find_orchid', 'role': role,
    }
    return render(request, "orchidlist/advanced.html", context)


@login_required
def genera(request):
    genus = ''
    min_lengenus_req = 2
    year = ''
    genustype = ''
    formula1 = ''
    formula2 = ''
    status = ''
    sort = ''
    prev_sort = ''
    sf_obj = ''
    t = ''
    role = 'pub'
    t_obj = ''
    st_obj = ''
    num_show = 5
    page_length = 1000
    # max_page_length = 1000
    if 'role' in request.GET:
        role = request.GET['role']
    alpha = ''
    if 'alpha' in request.GET:
        alpha = request.GET['alpha']

    if 'genus' in request.GET:
        genus = request.GET['genus']
        if len(genus) > min_lengenus_req:
            genus = str(genus).split()
            genus = genus[0]
    if 'sf' in request.GET:
        sf = request.GET['sf']
        if sf:
            sf_obj = Subfamily.objects.get(pk=sf)
    if 't' in request.GET:
        t = request.GET['t']
        if t:
            try:
                t_obj = Tribe.objects.get(pk=t)
            except Tribe.DoesNotExist:
                pass
            if not sf_obj:
                try:
                    sf_obj = Subfamily.objects.get(pk=t_obj.subfamily)       # back fill subfamily
                except Subfamily.DoesNotExist:
                    pass
    if 'st' in request.GET:
        st = request.GET['st']
        if st:
            try:
                st_obj = Subtribe.objects.get(pk=st)
            except Subtribe.DoesNotExist:
                pass
            if st_obj:
                if not t:
                    try:
                        t_obj = Tribe.objects.get(pk=st_obj.tribe.tribe)
                    except Tribe.DoesNotExist:
                        pass
                if not sf_obj and st_obj.subfamily:
                    try:
                        sf_obj = Subfamily.objects.get(pk=st_obj.subfamily)
                    except Subtribe.DoesNotExist:
                        pass

    # Remove genus choide if subfamily, tribe or subtribe is chosen
    if sf_obj or t_obj or st_obj:
        genus = ''
    year_valid = 0
    if 'year' in request.GET:
        year = request.GET['year']
        if valid_year(year):
            year_valid = 1

    if 'genustype' in request.GET:
        genustype = request.GET['genustype']
    if not genustype:
        genustype = 'all'
        
    if 'formula1' in request.GET:
        formula1 = request.GET['formula1']
    if 'formula2' in request.GET:
        formula2 = request.GET['formula2']

    if 'status' in request.GET:
        status = request.GET['status']

    genus_list = Genus.objects.all()
    if year_valid:
        year = int(year)
        genus_list = genus_list.filter(year=year)

    if genus:
        if len(genus) >= 2:
            genus_list = genus_list.filter(genus__icontains=genus)
        elif len(genus) < 2:
            genus_list = genus_list.filter(genus__istartswith=genus)

    if status == 'synonym':
        genus_list = genus_list.filter(status='synonym')

    elif genustype:
        if genustype == 'ALL':
            if year:
                genus_list = genus_list.filter(year=year)
        elif genustype == 'hybrid':
            genus_list = genus_list.filter(type='hybrid').exclude(status='synonym')
            if formula1 != '' or formula2 != '':
                genus_list = genus_list.filter(description__icontains=formula1).filter(description__icontains=formula2)
        elif genustype == 'species':
            # If an intrageneric is chosen, start from beginning.
            genus_list = genus_list.filter(type='species').exclude(status='synonym')
            if sf_obj or t_obj or st_obj:
                if sf_obj and t_obj and st_obj:

orchidlist/templates/orchidlist/browse_gen.html
{% load static %}
{% include "base.html" %}
{% block body %}

<style>
    /*Styles for Top Descendants*/
.row::after {
    content: "";
    clear: both;
    display: table;
}
[class*="col-"] {
    float: left;
    padding: 10px;
    margin-left: 15px;
    height: 100%;
}
.clearfix:after {
    content: "";
    display: table;
    clear: both;
}

label {
    display: inline-block;
    /*float: left;*/
    width: 250px;
    margin-right: 5px;
}

.imgcaption {
    font-size: 11px;
    height: 40px;
    overflow: hidden;
    word-wrap: normal;
    padding:0 3px;
   width : 100%;
}
.imgcaption_top {
    font-size: 15px;
    height: 20px;
    overflow: hidden;
}

.thumbnails {
   object-fit: cover;
   overflow: hidden;
   height: 17vw;
   width : 17vw;
   padding:2px;
}
div.text-n {
    font-size: 13px;
    font-weight:normal;
}

.box {
    position: relative;
    display: inline-block;
    text-align: center;
    color: white;
    margin:  3px 10px;
}
.imageitem {
    display:inline-block;
    border:1px solid grey;
    margin:0 2px;
    width : 19vw;
    /*height : 22vw;*/
    background-color: #eaeaea;
    border:1px solid lightgrey;
    text-align:center;
}

img{
    width:100%;
}

@media only screen and (max-width: 830px) {
    div.text-n {
        font-size: 10px;
    }

    .imageitem {
        width : 22vw;
    }
    .thumbnails {
       height: 19vw;
       width : 19vw;
    }
    .imgcaption_top {
        font-size: 12px;
    }
    .imgcaption {
        font-size: 10px;
        height: 52px;
       width : 20vw;
    }
}

@media only screen and (max-width: 600px) {
    div.text-n {
        font-size: 12px;
    }

    .thumbnails {
       height: 32vw;
       width : 32vw;
       /*padding:2px 1px 3px 1px;*/
    }
    .imgcaption_top {
        font-size: 12px;
    }
    .imgcaption {
        font-size: 9px;
        height: 40px;
        width : 32vw;
    }
   .imageitem {
        width: 36vw;
       /*height: 170px;*/
       /*border:1px solid red;*/
    }
}

.btn-group-xs > .btn, .btn-xs {
    padding  : 8px 30px;
    /*padding  : .5rem .5rem;*/
    font-size  : .8rem;
    line-height  : .65;
    border-radius : .2rem;
}
</style>
<div class="form-check-inline m-2 text-n">
    <form action="?" id="display">
        <input type="hidden" name="type" value="{{type}}" />
        <input type="hidden" name="role" value="{{role}}" />
        <input type="hidden" name="alpha" value="{{alpha}}" />
        <input type="hidden" name="page" value="{{page}}" />
        {% if display %}
            <input type="checkbox" class="form-check-input" name="display" value="checked" checked onchange="this.form.submit()">
        {% else %}
            <input form="display" type="checkbox" class="form-check-input" name="display" value="checked" onchange="this.form.submit()">
        {% endif %}
        Show {{type}} with images only?
    </form>
</div>
<div class="row d-flex m-2 justify-content-center align-items-center">
    <h4>Sample Images by Genera</h4>
    <a class="btn btn-xs btn-primary m-2" data-toggle="collapse" href="#Instruction">Instruction</a>
    <div id="Instruction" class="collapse" style="font-size:13px;width:90%">
        This page samples random images of species or hybrids for each genus. Each image is a link to sample images of species of that genus.
        <p>Two entry points to this page:
        from a link provided in the Home page or from the 'All genera images' option in the genus dropdown list in the top navbar.
        </p>
        <p>You may select type of samplings: species or hybrid, or select to see the list of species or hybrid names instead of photos.
        There also is a checkbox to display only species with images or to display all species with or whithout images.
        </p>
    </div>
</div>

<div class="container justify-content-center align-items-center" style="display:block; clear:left; margin: 0 auto; width: 95%">
    <!--Main table-->
    {% if type == 'species' %}
        <a type="button" class="btn btn-secondary btn-xs" disabled href="#">Species</a>
        <a type="button" class="btn btn-outline-secondary btn-xs" href="{% url 'orchidlist:browsegen' %}?type=hybrid&display={{display}}&alpha={{alpha}}">Hybrid</a>
    {% else %}
        <a type="button" class="btn btn-outline-secondary btn-xs" href="{% url 'orchidlist:browsegen' %}?type=species&display={{display}}&alpha={{alpha}}">Species</a>
        <div type="button" class="btn btn-secondary btn-xs" disabled href="#">Hybrid</div>
    {% endif %}


    {% if page_list %}


        {% include "orchidlist/alpha_list.html" %}
        {% if last_page > 1 %}
            {% include "orchidlist/paginator_brwgen.html" %}
        {% else %}
        {% endif %}
        {% for x in page_list %}
            <div class="imageitem m-1" style="display:inline-block; text-align:center;">
                <a href="{% url 'orchidlist:browse' %}?type={{type}}&genus={{x.genus}}&role={{role}}&display=checked">
                <div class="imgcaption_top">
                    {{x.genus|safe}}
                </div>
                    <img class="thumbnails" alt="" src="{% static x.image_file %}" class="img-fluid fullimg">
                </a>
                <div class="imgcaption flex-wrap border" >
                    {{x.namecasual|safe}},
                    {{x.author}} {{x.year}}
                    <br>{{x.imginfo }}
                </div>
            </div>
        {% endfor %}
        <div class="clearfix"></div>
    {% else %}
        <div style="text-align: center;padding-top:20px">None</div>
    {% endif %}
</div>

	<script type="text/javascript">

$(document).ready(function(){
    $('a[data-toggle="tab"]').on('show.bs.tab', function(e) {
        localStorage.setItem('activeTab', $(e.target).attr('href'));
    });
    var activeTab = localStorage.getItem('activeTab');
    if(activeTab){
        $('#myTab a[href="' + activeTab + '"]').tab('show');
    }
});

$(document).on('click', '[data-toggle="lightbox"]', function(event) {
                event.preventDefault();
                $(this).ekkoLightbox();
            });



</script>


{% endblock %}

orchidlist/templates/orchidlist/subtribe.html
{% load static %}
{% include "base.html" %}
{% block body %}

<style>
  table.center {
      width:80%;
      margin-left:auto;
      margin-right:auto;
      font-size:13px;
  }
.scrollable-menu {
    height: auto;
    max-height: 200px;
    overflow-x: hidden;
}
</style>
<br><br><br>

<div style="margin:0 0 0 0; padding:5px 0 5px 0; text-align: center; border:0 solid grey">
    <div class="container" style="text-align:center;">
        <h4><b>{{sf}} {{t}} Subtribe</b></h4>
    </div>
    <div style="display:inline-block;">
      <label>Subfamily</label>
        <button class="dropdown-toggle" type="button" data-toggle="dropdown" style="height:27px; font-size:12px;text-align:left;background-color: white;border:1px solid #ccc">
                {% if sf %}{{sf}}{% else %}<span class="txt" style="font-size:12px; color:#bdaec6">Subfamily</span>{% endif %}
        </button>
        <div class="dropdown-menu scrollable-menu" style="font-size: 11px;padding:0;width:80px;">
            <a class="dropdown-item" href="{%url 'orchidlist:subtribe' %}?sf=&t={{t}}">&nbsp;</a>
            {% for x in sf_list %}
            <a class="dropdown-item" href="{%url 'orchidlist:subtribe' %}?sf={{x}}&t={{t}}">{{x}}</a>
            {% endfor %}
        </div>
    </div>
    <div style="display:inline-block;">
      <label>Tribe</label>
        <button class="dropdown-toggle" type="button" data-toggle="dropdown" style="height:27px; font-size:12px;text-align:left;background-color: white;border:1px solid #ccc">
            {% if t %}{{t}}{% else %}<span class="txt" style="font-size:12px; color:#bdaec6">Tribe</span>{% endif %}
        </button>
        <div class="dropdown-menu scrollable-menu" style="font-size: 11px;padding:0;width:80px;">
            <a class="dropdown-item" href="{%url 'orchidlist:subtribe' %}?sf={{sf}}">&nbsp;</a>
            {% for x in t_list %}
            <a class="dropdown-item" href="{%url 'orchidlist:subtribe' %}?sf={{sf}}&t={{x}}">{{x}}</a>
            {% endfor %}
        </div>
    </div>
</div>


{% if subtribe_list %}
    <div>
        <table class="table mytable table-bordered table-sm table-hover center">
            <tr>
				<th>Subfamily</th></th><th>Tribe </th><th>subtribe</th><th>author</th><th>year</th><th> Description</th>
			</tr>
			{% for subtribe in subtribe_list %}
			<tr>
				<td><a href="{% url 'orchidlist:genera' %}?sf={{subtribe.subfamily}}&genustype=species">{{subtribe.subfamily}}</a></td>
				<td><a href="{% url 'orchidlist:genera' %}?sf={{subtribe.subfamily}}&t={{subtribe.tribe}}&genustype=species">{{subtribe.tribe}}</a></td>
				<td><a href="{% url 'orchidlist:genera' %}?sf={{subtribe.subfamily}}&t={{subtribe.tribe}}&st={{subtribe.subtribe}}&genustype=species">{{subtribe.subtribe}}</a></td>
				<td style="font-size: 11px">{% if subtribe.author %}{{ subtribe.author }}{% endif %}</td>
				<td align=center>{% if subtribe.year %}{{subtribe.year}}{% endif %}</td>
				<td align=center>{% if subtribe.description %}{{subtribe.description}}{% endif %}</td>
			</tr>
			{% endfor %}
		</table>
	</div>
{% else %}
   <div style="text-align: center">None</div>
{% endif %}


{% endblock %}