detail/urls.py
from django.urls import path
from . import views

# TODO: Add a new page: Compare two species/hybrids
# TODO: Add feature search page - search by color, features
# TODO: Add search by ancestors pair.
# TODO: Add search by location

app_name = 'detail'
urlpatterns = [
    # detail
    # path('selectspecies/<int:pid>/', views.selectspecies, name='selectspecies'),
    # path('nav/', views.nav, name='nav'),
    path('species/', views.information, name='information'),
    path('species/<int:pid>/', views.information, name='information'),
    path('hybrid/', views.information, name='information'),
    path('hybrid/<int:pid>/', views.information, name='information'),
    path('<int:pid>/species/', views.information, name='information'),
    path('<int:pid>/species_detail/', views.information, name='information'),
    path('<int:pid>/hybrid/', views.information, name='information'),
    path('<int:pid>/hybrid_detail/', views.information, name='information'),
    path('compare/<int:pid>/', views.compare, name='compare'),
    path('compare/', views.compare, name='compare'),
    path('createhybrid/', views.createhybrid, name='createhybrid'),
    path('information/<int:pid>/', views.information, name='information'),
    path('information/', views.information, name='information'),

    path('ancestor/', views.ancestor, name='ancestor'),
    path('ancestor/<int:pid>/', views.ancestor, name='ancestor'),
    path('ancestrytree/<int:pid>/', views.ancestrytree, name='ancestrytree'),
    path('ancestrytree/', views.ancestrytree, name='ancestrytree'),
    path('progeny/<int:pid>/', views.progeny, name='progeny'),
    path('progenyimg/<int:pid>/', views.progenyimg, name='progenyimg'),

    path('comment/', views.comment, name='comment'),
    path('comments/', views.comments, name='comments'),
    path('myphoto/<int:pid>/', views.myphoto, name='myphoto'),
    path('myphoto/', views.myphoto, name='myphoto'),
    path('myphoto_browse_spc/', views.myphoto_browse_spc, name='myphoto_browse_spc'),
    path('myphoto_browse_hyb/', views.myphoto_browse_hyb, name='myphoto_browse_hyb'),
    path('curate/<int:pid>/', views.curate, name='curate'),
    path('<int:pid>/photos/', views.photos, name='photos'),
    path('photos/<int:pid>/', views.photos, name='photos'),
    path('curateinfospc/<int:pid>/', views.curateinfospc, name='curateinfospc'),
    path('curateinfospc/', views.curateinfospc, name='curateinfospc'),
    path('curateinfohyb/<int:pid>/', views.curateinfohyb, name='curateinfohyb'),
    path('curateinfohyb/', views.curateinfohyb, name='curateinfohyb'),
    path('curate_newupload/', views.curate_newupload, name='curate_newupload'),
    path('curate_pending/', views.curate_pending, name='curate_pending'),
    path('curate_newapproved/', views.curate_newapproved, name='curate_newapproved'),
    path('reidentify/<int:orid>/<int:pid>/', views.reidentify, name='reidentify'),

    path('uploadfile/<int:pid>/', views.uploadfile, name='uploadfile'),
    path('uploadweb/<int:pid>/', views.uploadweb, name='uploadweb'),
    path('uploadweb/<int:pid>/<int:orid>/', views.uploadweb, name='uploadweb'),
    path('deletephoto/<int:orid>/', views.deletephoto, name='deletephoto'),
    path('deletewebphoto/<int:pid>/', views.deletewebphoto, name='deletewebphoto'),
    path('approvemediaphoto/<int:pid>/', views.approvemediaphoto, name='approvemediaphoto'),
]

documents/urls.py
from django.urls import path
from . import views

# Documentations

app_name = 'documents'
urlpatterns = [
    # path('about/', views.about, name='about'),
    path('articles/', views.articles, name='articles'),
    path('bylaws/', views.bylaws, name='bylaws'),
    path('changes/', views.changes, name='changes'),
    path('contact/', views.contact, name='contact'),
    path('curator/', views.curator, name='curator'),
    path('development/', views.development, name='development'),
    path('datamodel/', views.datamodel, name='datamodel'),
    path('disclaimer/', views.disclaimer, name='disclaimer'),
    path('faq/', views.faq, name='faq'),
    path('future_development/', views.future_development, name='future_development'),
    path('greetings/', views.greetings, name='greetings'),
    path('help/', views.help, name='help'),
    path('identinstruction/', views.identinstruction, name='identinstruction'),
    # path('instructionupload_curate/', views.instructionupload_curate, name='instructionupload_curate'),
    # path('instructionupload_private/', views.instructionupload_private, name='instructionupload_private'),
    # path('instructionupload_file/', views.instructionupload_file, name='instructionupload_file'),
    path('instructionupload/', views.instructionupload, name='instructionupload'),
    path('list/', views.list, name='list'),
    path('migration/', views.migration, name='migration'),
    path('maintenance/', views.maintenance, name='maintenance'),
    path('navigation/', views.navigation, name='navigation'),
    path('photosubmissionguideline/', views.photosubmissionguideline, name='photosubmissionguideline'),
    path('photoacquisionguideline/', views.photoacquisionguideline, name='photoacquisionguideline'),
    path('privacy_policy/', views.privacy_policy, name='privacy_policy'),
    path('req501c3/', views.req501c3, name='req501c3'),
    path('releasenote_v4/', views.releasenote_v4, name='releasenote_v4'),
    path('termsofuse/', views.termsofuse, name='termsofuse'),
    path('whoweare/', views.whoweare, name='whoweare'),

    # path('assets/$', views.assets, name='assets'),
    # path('copyright/', views.copyright, name='copyright'),
    # path('newrelease/', views.newrelease, name='newrelease'),
    # path('personnel/', views.personnel, name='personnel'),
    # path('project/', views.project, name='project'),
    # path('statistics/', views.statistics, name='statistics'),
    # path('submission/', views.photo_submission, name='submission'),
    # path('rvolunteer/', views.volunteer, name='volunteer'),
]

donation/urls.py
from django.urls import path, re_path

from . import views

app_name = 'donation'
urlpatterns = [
    path('donateapp/', views.DonateView.as_view(), name='donateapp'),
    path('donateapp/<int:donateamt>/', views.DonateView.as_view(), name='donateapp'),
    path('donate/', views.donate, name='donate'),
    path('donate/<int:donateamt>/', views.donate, name='donate'),
    path('donate/paypal-done/', views.PaypalTransactionDoneView.as_view(), name='paypal-done'),
    path('thank-you/<int:donateamt>/', views.ThankYouView.as_view(), name='thankyou'),
]

myproject/urls.py
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.generic import TemplateView
from django.views.generic.base import TemplateView
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from accounts.views import  user_reset_password, login_page, register_page, UpdateProfileView, SetEmailView,\
    ChangeEmailView, PasswordChangeRedirect, CustomPasswordResetFromKeyView
from myproject.views import orchid_home
from myproject.views import robots_txt

urlpatterns = [
    path('admin/', admin.site.urls),
    # path("robots.txt", robots_txt),
    path("robots.txt", TemplateView.as_view(template_name="robots.txt", content_type="text/plain"),
    path('', orchid_home, name='orchid_home'),

    path('login/', login_page, name='login'),
    path('register/', register_page, name='register'),
    path('set_email/', SetEmailView.as_view(), name='set_email'),
    path('change_email/', ChangeEmailView.as_view(), name='change_email'),
    path('update_profile/', UpdateProfileView.as_view(), name='update_profile'),
    path('logout/', LogoutView.as_view(), {'next_page': '//'}, name='logout'),
    path('accounts/password/change/', PasswordChangeRedirect.as_view(), name="account_password_change"),
    
    path('accounts/password/user_reset_password/', user_reset_password, name="user_account_reset_password"),
    re_path(
        r"^accounts/password/reset/key/(?P<uidb36>[0-9A-Za-z]+)-(?P<key>.+)/$",
        CustomPasswordResetFromKeyView.as_view(),
        name="account_reset_password_from_key",
    ),
    path('accounts/', include('allauth.urls')),
    # path('password_reset/', include(password_reset.urls)),

    path('search/', include('search.urls')),
    path('orchidlist/', include('orchidlist.urls')),
    path('detail/', include('detail.urls')),
    path('documents/', include('documents.urls')),
    path('donation/', include('donation.urls')),

    # old
    path('natural/', include('natural.urls')),
    path('orchid/', include('orchid.urls')),
    path('orchidlite/', include('orchidlite.urls')),

    # path('sendmail/', include('sendmail.urls')),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

documents/models.py
from django.db import models

# Create your models here.

documents/views.py
from django.shortcuts import render
from django.apps import apps
from django.contrib.auth.decorators import login_required

User = apps.get_model('accounts', 'User')

# Create your views here.
def list(request):
    context = {}
    return render(request, 'documents/list.html', context)

def help(request):
    context = {}
    return render(request, 'documents/help.html', context)

def releasenote_v4(request):
    context = {}
    return render(request, 'documents/releasenote_v4.html', context)

def bylaws(request):
    context = {}
    return render(request, 'documents/bylaws.html', context)

def articles(request):
    context = {}
    return render(request, 'documents/articles_of_incorporation.html', context)

def req501c3(request):
    context = {}
    return render(request, 'documents/req501c3.html', context)

def disclaimer(request):
    context = {}
    return render(request, 'documents/disclaimer.html', context)

def termsofuse(request):
    context = {}
    return render(request, 'documents/termsofuse.html', context)


@login_required
def future_development(request):
    # if request.user.tier.tier < 5:
    #     return HttpResponseRedirect(reverse('/'))
    context = {}
    return render(request, 'documents/future_development.html', context)


def greetings(request):
    context = {}
    return render(request, 'documents/greetings.html', context)


def faq(request):
    context = {}
    return render(request, 'documents/faq.html', context)

def curator(request):
    curator_list = User.objects.filter(tier=3).order_by('fullname')
    context = {'curator_list':curator_list}
    return render(request, 'documents/curator.html', context)

@login_required
def migration(request):
    # if request.user.tier.tier < 5:
    #     return HttpResponseRedirect(reverse('/'))
    context = {}
    return render(request, 'documents/migration.html', context)

@login_required
def maintenance(request):
    # if request.user.tier.tier < 5:
    #     return HttpResponseRedirect(reverse('/'))
    context = {}
    return render(request, 'documents/maintenance.html', context)


def navigation(request):
    context = {}
    return render(request, 'documents/navigation.html', context)


def identinstruction(request):
    context = {}
    return render(request, 'documents/identinstruction.html', context)

def datamodel(request):
    context = {}
    return render(request, 'documents/datamodel.html', context)


def photosubmissionguideline(request):
    context = {}
    return render(request, 'documents/photosubmissionguideline.html', context)

def photoacquisionguideline(request):
    context = {}
    return render(request, 'documents/photoacquisitionguideline.html', context)


def instructionupload_curate(request):
    context = {}
    return render(request, 'documents/instructionupload_curate.html', context)


def instructionupload_private(request):
    context = {}
    return render(request, 'documents/instructionupload_private.html', context)


def instructionupload(request):
    context = {}
    return render(request, 'documents/instructionupload.html', context)


def development(request):
    context = {}
    return render(request, 'documents/development.html', context)


def changes(request):
    context = {}
    return render(request, 'documents/changes.html', context)


def termofuse(request):
    context = {}
    return render(request, 'documents/termofuse.html', context)


def privacy_policy(request):
    context = {}
    return render(request, 'documents/privacy_policy.html', context)


def contact(request):
    context = {}
    return render(request, 'documents/contact.html', context)


def whoweare(request):
    context = {}
    return render(request, 'documents/whoweare.html', context)

documents/templates/documents/changes1.html

                    <h6 class="mb-0">User Accounts</h6>
                    <ul>
                        <li><b>Authentication</b>: User must sign in with unique user id and email.  A confirmation email will be sent after a successful registration or after an email change request.</li>
                        <li><b>Password reset</b>: User can reset password</li>
                        <li><b>Change email</b>: User can change and revalidate email</li>
                        <li><b>Socialmedia login</b>: User can login with active Facebook account.</li>
                    </ul>
                    <br>

                    <h6 class="mb-0">Search and Lists</h6>
                    The dropdown list of genera, species and hybrids were removed from navbar at the top of eveery page.  These lists
                    are moved to a new page "Advanced Search".  The move is necessary to
                    improve page load speed.  The new Advanced Search view provides several options to make it navigate the site.
                    you can select a specific species or hybrid and go directly to its detail page,

                    <br>
                    <br>
                    <h6 class="mb-0">
                        Three Access levels
                    </h6>
                        <ul>
                            <li><b>Basic view</b>: Anonymous Users can access public pages, search, browse images and detail pages.</li>
                            <li><b>Private view</b>: Registered Users can access all features in the basic level including ability to upload and manage their own photos in their private album.
                                    Registered users can also view filtered lists of species and hybrids.</li>
                            <li><b>Curate view</b>: Registered Curators can access all features in the private level including the ability to approve or reject private photos.  Curators can also
                                reidentify a miss-identified photo and update information related to a species of hybrid.</li>
                        </ul>
                    <br>
                    <h6 class="mb-0">Detail Page</h6>
                    <ul>
                        <li><b>Summary tab</b>:  This page shows a short selection of public photos that best represents the defining characteristics of the orchid. The page includes a summary of taxonomy,
                            and other information related to the orchid.  Photos of parents and species ancestors are also shown for hybrid.
                        <li><b>Photo tab</b>: This view combines public and private photos, where private photos are visible to their owner only.
                        This simplifies navigation and allows users to view all public and private photos in the same page.  A number of control buttons in this view allow registered users
                        to select species or hybrid containing their photos. Registered curators will see a different sets of control buttons that allow them to manage photos such as approving, setting status,
                        or reidentifing.</li>
                        <li><b>Compare tab</b>: Allow users to compare two species side by side and create a new hybrid if the cross between the two orchids does not exist in OrchidRoots.</li>
                    </ul>
                    <br>
                    <h6 class="mb-0">Donate function</h6>
                    We have registered for a donate function on Paypal to make it convenient for users to help with our cause. Please consider making a
                    <a href="{% url 'donation:donateapp' %}">donation</a> today... thank you!



documents/templates/documents/faq.html
{% load static %}
{% include "base.html" %}
{% block body %}

<br><br>
<div class="container" style="text-align:center;border:0 solid blue">
    <h3>FAQ</h3>
    <h4>Future Plans</h4>
    <ul>
        <li>How does OrchidRoots resolve a conflict between WCSP and RHS?</li>
        <li>Are there plans for mobile apps?</li>
        <li>Are there plans to support other plant families?</li>
        <li>I have a question that's not covered here. Help!</li>
    </ul>
</div>

{% endblock %}

documents/templates/documents/help.html
{% load static %}
{% include 'base.html' %}

<style>
.doc {
    overflow-wrap: break-word;
    font-size: 14px;
    padding:10px;
    margin:0 auto;
    border:1px solid lightgrey;
}
.btn {
    margin:2px 0;
    width: 95%;
    font-size:11px;
    color: #272ba3;
    padding:5px 0;
    background-color: white;
    border:1px solid #c6c0c0;
    border-radius: .15rem;
}
.btn:hover {
    background-color: #cad4f7;
}

</style>
<br>
<div style="clear:both"></div>
<br>
<div class="container-fluid" style="min-height:200px;border:0 solid grey">
    <div style="clear:both"></div>
	<div class="row">
        <div class="d-none d-sm-block col-sm-3 col-lg-2" style="padding:0; border:1px solid lightgrey">
            {% include "side_home.html" %}
        </div>

        <div class="col-sm-8 col-lg-9">

            <div style="margin:0 auto; width:70%;">

                <div style="font-size: 14px; padding:10px; margin:0 auto; border:1px solid lightgrey; ">
                    <a href="{% url 'documents:articles' %}" target="_blank">Article Of Incorporation</a>
                </div>
                <br>
                <div style="font-size: 14px; padding:10px; margin:0 auto; border:1px solid lightgrey; ">
                    <a href="{% url 'documents:bylaws' %}" target="_blank">Bylaws</a>
                </div>
                <br>
                <div style="font-size: 14px; padding:10px; margin:0 auto; border:1px solid lightgrey; ">
                    <a href="{% url 'documents:req501c3' %}" target="_blank">Application for Recognition of Exemption Under 501(c)(3) of the Internal Revenue Code</a>
                </div>
                <br>

                <div style="font-size: 14px; padding:10px; margin:0 auto; border:1px solid lightgrey; ">
                     Maryland Association of Nonprofit Organizations, Conflic of Interest
                </div>
                <br>
            </div>
        </div>
    </div>
</div>



documents/templates/documents/list.html
{% load static %}
{% include 'base.html' %}

<style>
    ul{
        padding-left:10px;
        line-height: 30px;
        list-style-type:none;
    }
    li {
            display: list-item;
    }
    .card-body {
        font-size: 15px;
    }
    .sidebtn {
        text-align: left;
        width: 200px;
    }
</style>
<br>

<div class="container-fluid" style="min-height:200px;">
    <div style="clear:both"></div>
    <div class="row">
        <div class="d-none d-sm-block col-sm-3 col-lg-2 ">
            {% include "side_home.html" %}
        </div>

        <div class="col-sm-7 col-lg-8" style="margin-top:7px;">
            <div id="accordion">
<!--                Privacy policy-->
                <div class="card mt-3">
                    <div class="card-header">
                        <h6 class="card-title" style="margin-bottom: 0">Policies</h6>
                    </div>
                    <div class="card-body">
                        <button type="button" class="btn btn-xs info-collapse sidebtn" data-toggle="collapse" data-target="#Privacy">Privacy policy</button>
                        <div id="Privacy" class="collapse" data-parent="#accordion">
                            <div class="card-body">
                                {% include 'documents/privacy_policy1.html' %}
                            </div>
                        </div>
        <!--                Terms of Use-->
                        <button type="button" class="btn btn-xs info-collapse sidebtn" data-toggle="collapse" data-target="#TermsofUse">Terms of Use</button>
                        <div id="TermsofUse" class="collapse" data-parent="#accordion">
                            <div class="card-body">
                                {% include 'documents/termsofuse1.html' %}
                            </div>
                        </div>
                    </div>
                </div>

                <div class="card mt-3">
                    <div class="card-header">
                        <h6 class="card-title" style="margin-bottom: 0">Instruction</h6>
                    </div>
                    <div class="card-body">
                <!--                Upload instruction-->
                        <button type="button" class="btn btn-xs info-collapse sidebtn" data-toggle="collapse" data-target="#Webupload">Upload from a webpage</button>
                        <div id="Webupload" class="collapse" data-parent="#accordion">
                            <div class="card-body">
                                {% include 'documents/instructionupload1.html' %}
                            </div>
                        </div>

<!--                Photo Submission Policy-->
                        <button type="button" class="btn btn-xs info-collapse sidebtn" data-toggle="collapse" data-target="#Submission">Photo submission policy</button>
                        <div id="Submission" class="collapse" data-parent="#accordion">
                            <div class="card-body">
                                {% include 'documents/photosubmissionguideline1.html' %}
                            </div>
                        </div>
                    </div>
                </div>
<!--                Maintenance-->
                <div class="card mt-3">
                    <div class="card-header">
                        <h6 class="card-title" style="margin-bottom: 0">Maintenance</h6>
                    </div>
                    <div class="card-body">
                <!--                Upload instruction-->
                        <button type="button" class="btn btn-xs info-collapse sidebtn" data-toggle="collapse" data-target="#Maintenance">Scheduled Maintenance</button>
                        <div id="Maintenance" class="collapse" data-parent="#accordion">
                            <div class="card-body">
                                {% include 'documents/maintenance.html' %}
                            </div>
                        </div>
                <!--                Upload instruction-->
                        <button type="button" class="btn btn-xs info-collapse sidebtn" data-toggle="collapse" data-target="#WCSP">WCSP Upload</button>
                        <div id="WCSP" class="collapse" data-parent="#accordion">
                            <div class="card-body">
                                {% include 'documents/datasources/WCSP.html' %}
                            </div>
                        </div>
<!--                                IOA Upload-->
                        <button type="button" class="btn btn-xs info-collapse sidebtn" data-toggle="collapse" data-target="#IOA">IOA Upload</button>
                        <div id="IOA" class="collapse" data-parent="#accordion">
                            <div class="card-body">
                                {% include 'documents/datasources/IOA.html' %}
                            </div>
                        </div>




                    </div>
                </div>

<!--                Release Notes-->
                <div class="card mt-3">
                    <div class="card-header">
                        <h6 class="card-title" style="margin-bottom: 0">Release Notes</h6>
                    </div>
                    <div class="card-body" style="padding:10px;">

    <!--                V. 3.1-->
                        <button type="button" class="btn btn-xs info-collapse sidebtn" data-toggle="collapse" data-target="#Change1">OrchidRoots V.3.1 - 2020-10-01</button>
                        <div id="Change1" class="collapse" data-parent="#accordion">
                            <div class="card-body">
                                {% include 'documents/changes1.html' %}
                            </div>
                        </div>

    <!--                V. 3.0-->
                        <button type="button" class="btn btn-xs info-collapse sidebtn" data-toggle="collapse" data-target="#Change2">OrchidRoots V.3 - 2019/06/01</button>
                        <div id="Change2" class="collapse" data-parent="#accordion">
                            <div class="card-body">
                                {% include 'documents/changes2.html' %}
                            </div>
                        </div>

    <!--                Bluenanta -->
                        <button type="button" class="btn btn-xs info-collapse sidebtn" data-toggle="collapse" data-target="#Change3">BlueNanta V.1.0 - 2015-?-?</button>
                        <div id="Change3" class="collapse" data-parent="#accordion">
                            <div class="card-body">
                                TBD
                            </div>
                        </div>


                    {% if user.tier.tier > 3 %}
    <!--                Bluenanta -->
                            <button type="button" class="btn btn-xs info-collapse sidebtn" data-toggle="collapse" data-target="#migration">Deployment Procedures</button>
                            <div id="migration" class="collapse" data-parent="#accordion">
                                <div class="card-body">
                                    TBD
                                </div>
                            </div>

    <!--                Bluenanta -->
                            <button type="button" class="btn btn-xs info-collapse sidebtn" data-toggle="collapse" data-target="#Change3">BlueNanta V.1.0 - 2021-?-?</button>
                            <div id="Change3" class="collapse" data-parent="#accordion">
                                <div class="card-body">
                                    TBD
                                </div>
                            </div>

                    {% endif %}
                    </div>
                </div>
            </div>

<!--                Public-->
            <div class="card mt-3">
                <div class="card-header">
                    <h6 class="card-title" style="margin-bottom: 0">Public inspection requirements</h6>
                </div>

                <div class="card-body" style="padding:10px;">

                    "Tax-exempt organizations must make annual returns and exemption applications filed with
                    the IRS available for public inspection and copying upon request..." [The IRS].<br>
                    To conform with this reqirement, all relevant forms and publications are posted below.
                    <br>

                    <ul>
                        <li>
                            <a href="{% url 'documents:articles' %}" target="_blank">Article Of Incorporation</a>
                        </li>
                        <li>
                            <a href="{% url 'documents:bylaws' %}" target="_blank">Bylaws</a>
                        </li>
                        <li>
                            <a href="{% url 'documents:req501c3' %}" target="_blank">Application for Recognition of Exemption Under 501(c)(3) of the Internal Revenue Code</a>
                        </li>
                       <li>
                             Maryland Association of Nonprofit Organizations, Conflic of Interest
                        </li>
                    </ul>
                </div>

    <!--                <div style="margin:0 auto;border:1px solid lightgrey;">-->
    <!--                    <div class="btn" href="">Tax (Form 990-PF)</div>-->
    <!--                    <div class="btn" href="">2019</div>-->
    <!--                    <div class="btn" href="">2020</div>-->
    <!--                    <div class="btn" href="">2021</div>-->
    <!--                    <div class="btn" href="">2022</div>-->
    <!--                    <div class="btn" href="">2023</div>-->
    <!--                </div>-->


            </div>
        </div>
    </div>
</div>

documents/templates/documents/maintenance.html

<ul>
    <li>Data Sources
        <ul>
            <LI>Catalog of Life: get supra generic records.  Process 100% manual.</LI>
            <li>BCR: Bromeliaceae hybrids.  Process is 40% manual. </li>
            <li>WCSP: Process 30% manual</li>
            <li>RHS: 20% manual</li>
            <li>IPNI: infra gneric data</li>
            <li>IOSPE: Orchidaceae culture and infra generic</li>
        </ul>
    </li>
    <li>Cron Tasks
        <ul>
            <li>5 minutes: Generate images for new upload from web</li>
            <li>5 minutes: Sync new accounts to photographer</li>
            <li>5 minutes: Update ancestor descendant relation</li>
            <li>daily: refresh genus / species images stat</li>
            <li>daily: refresh anc/desc count for genus</li>
        </ul>
    </li>
    <li>Daily Tasks
        <ul>
            <li>Approve uploade photos</li>
            <li>Monitor Upload traffic and file growth in digital ocean</li>
            <li>Monitor comments</li>
            <li>Monitor new accounts and create profile, photographer</li>
        </ul>
    </li>
    <li>Weekly Tasks
        <ul>
            <li>Data integrity: Various SQL scripts</li>
            <li>monitor total file and directory size</li>
            <li>monitor historical update (approve, reject, reidentify, delete)</li>
        </ul>
    </li>
    <li>Monthly Tasks
        <ul>
            <li>Update WCSP: monthly</li>
            <li>Update RHS: Monthly</li>
            <li>Run python manage.py clearsessions once a month to truncate django sessions</li>
        </ul>
    </li>
    <li>Yearly task
        <ul>
            <li>RHS Changes: Yearly (100% manual)</li>
            <li>IPNI: yearly</li>
            <li>Update GenusRelation (yearly or each time a new genus is created)</li>
            <li>Update Taxonomy (yearly or each time there is a change in Genus related to subfamily/tribe/subtribe)</li>
            <li>WCSP: Update Distribution code (yearly)</li>
            <li>Clean up django migrations</li>
        </ul>
    </li>

    <li>TODO
        <ul>
            <li>Scripts to compute stats and store in a new database (in core app)</li>
        </ul>
    </li>
</ul>